export type HeroWithin30Day = {
  day: number;
  week: number;
  theme: string;
  title: string;
  focus: string;
  reflection: string;
  strength: string;
  move: string;
  affirmation: string;
};

export const HERO_WITHIN_30_DAY_VERSION = "30-day-foundation-v0.1";
export const HERO_WITHIN_30_DAY_AUDIO_STATUS = "studio-master-pending" as const;

export const HERO_WITHIN_30_DAY: HeroWithin30Day[] = [
  { day: 1, week: 1, theme: "Make Space", title: "Arrive Before You Act", focus: "Notice where you are before deciding where to go.", reflection: "What feels most present in your mind, body, or surroundings right now?", strength: "What helps you become a little more steady without forcing the feeling away?", move: "Give yourself two uninterrupted minutes to notice, breathe naturally, stretch, pray, sit, or step outside.", affirmation: "I can arrive in this moment before I choose my next move." },
  { day: 2, week: 1, theme: "Make Space", title: "Name What Matters", focus: "Clear words create a clearer starting point.", reflection: "What feeling, challenge, decision, or responsibility needs an honest name today?", strength: "What do you understand now that you did not understand a week ago?", move: "Complete this sentence in your own words: The real thing I want to address is…", affirmation: "Naming the moment helps me work with the moment." },
  { day: 3, week: 1, theme: "Make Space", title: "Separate Fact from Story", focus: "Facts and interpretations are both useful when you know which is which.", reflection: "What do you know happened, and what are you assuming, predicting, or interpreting?", strength: "When have you slowed down enough to see a situation more clearly?", move: "Write one fact, one feeling, and one open question before making a conclusion.", affirmation: "I can make room for what I know and what I still need to learn." },
  { day: 4, week: 1, theme: "Make Space", title: "Notice the Pressure", focus: "Pressure becomes easier to work with when you can see its source.", reflection: "What expectation, deadline, fear, comparison, or responsibility is adding pressure today?", strength: "Which part of this pressure have you handled before, even imperfectly?", move: "Choose one pressure you can reduce, delay, delegate, question, or discuss with someone safe.", affirmation: "I do not have to treat every pressure as an emergency." },
  { day: 5, week: 1, theme: "Make Space", title: "Find Five Percent More Calm", focus: "Small shifts can create useful room for choice.", reflection: "What would five percent more calm, space, or steadiness look like right now?", strength: "Which ordinary action tends to help you reset without demanding that you feel perfect?", move: "Try one low-pressure reset for five minutes and notice what changes, if anything.", affirmation: "A small reset can be enough to help me choose well." },
  { day: 6, week: 1, theme: "Make Space", title: "Choose What Can Wait", focus: "Not everything deserves the same urgency.", reflection: "What are you carrying today that does not truly need your attention right now?", strength: "What value helps you decide what deserves priority?", move: "Move one non-urgent item to a later time and protect the space you just created.", affirmation: "I can choose what gets my attention." },
  { day: 7, week: 1, theme: "Make Space", title: "Reflect on the Week", focus: "Notice what helped before adding more.", reflection: "What did you learn this week about your pressure, attention, or emotional space?", strength: "Which strength showed up most often, even quietly?", move: "Write one sentence about what you want to keep practicing next week.", affirmation: "Reflection helps me carry learning forward." },

  { day: 8, week: 2, theme: "Strength & Support", title: "Remember a Strength", focus: "Strength is evidence, not a slogan.", reflection: "Think of a recent moment when you handled something difficult with care, patience, courage, honesty, or persistence. What did you actually do?", strength: "Which strength was visible in that action?", move: "Use that same strength once today in a small, deliberate way.", affirmation: "I can use evidence from my own life to remember what I carry." },
  { day: 9, week: 2, theme: "Strength & Support", title: "Use What Already Works", focus: "You do not have to reinvent every solution.", reflection: "What routine, person, place, tool, or practice has helped you before?", strength: "What made it useful instead of just familiar?", move: "Reuse one proven support today and adjust it to fit the current moment.", affirmation: "I can return to what helps and make it useful again." },
  { day: 10, week: 2, theme: "Strength & Support", title: "Ask a Better Question", focus: "A better question can create a better next move.", reflection: "What question have you been asking yourself that leads mostly to blame, fear, or stuckness?", strength: "What would a more useful question sound like?", move: "Rewrite one stuck question into a question about choices, support, learning, or next steps.", affirmation: "I can ask questions that help me move instead of trap me." },
  { day: 11, week: 2, theme: "Strength & Support", title: "Name the Value Underneath", focus: "Values can guide choices when emotions are loud.", reflection: "What value matters underneath this situation: respect, safety, family, learning, fairness, responsibility, creativity, faith, health, or something else?", strength: "When have you acted in line with that value before?", move: "Choose one action today that reflects the value you named.", affirmation: "My values can help me choose even when the moment is complicated." },
  { day: 12, week: 2, theme: "Strength & Support", title: "Borrow Perspective", focus: "You can learn from another viewpoint without giving away your judgment.", reflection: "Whose perspective could help you see this situation more clearly or fairly?", strength: "What makes that person, source, or viewpoint trustworthy enough to consider?", move: "Ask one thoughtful question or review one reliable perspective before deciding your next step.", affirmation: "I can listen, learn, and still make my own choice." },
  { day: 13, week: 2, theme: "Strength & Support", title: "Reach for Support", focus: "Connection can be a form of strength.", reflection: "Where would support, accountability, information, or encouragement make this moment easier to carry?", strength: "Who is a safe person or reliable resource you can reach toward?", move: "Send one message, ask one question, or schedule one conversation.", affirmation: "Asking for support can be a powerful Hero Move." },
  { day: 14, week: 2, theme: "Strength & Support", title: "Reflect on Your Support System", focus: "Support works best when you know what kind you need.", reflection: "What kind of support helped most this week: listening, information, accountability, encouragement, practical help, or space?", strength: "How did you contribute to your own support system?", move: "Write one way you will make support easier to access next week.", affirmation: "I can build support intentionally instead of waiting until I am overwhelmed." },

  { day: 15, week: 3, theme: "Hero Moves & Boundaries", title: "Shrink the Next Step", focus: "Progress becomes easier to begin when the next action is clear and small.", reflection: "What outcome are you trying to reach, and what is the smallest useful step toward it?", strength: "What skill or resource makes that small step realistic?", move: "Choose one action you can begin in fifteen minutes or less.", affirmation: "My next move does not have to solve everything to matter." },
  { day: 16, week: 3, theme: "Hero Moves & Boundaries", title: "Begin Before You Feel Ready", focus: "Readiness often grows after a safe first step.", reflection: "What are you waiting to feel before you begin?", strength: "What evidence suggests you already have enough to take one careful step?", move: "Start the first safe, reversible part of the task and stop after ten focused minutes if you need to.", affirmation: "I can begin without pretending I know every step." },
  { day: 17, week: 3, theme: "Hero Moves & Boundaries", title: "Practice a Boundary", focus: "A boundary protects what matters; it is not a punishment.", reflection: "Where do you need a clearer limit around your time, attention, access, energy, or responsibility?", strength: "What value would that boundary protect?", move: "State or write one respectful boundary using clear, specific language.", affirmation: "I can protect what matters without becoming unkind." },
  { day: 18, week: 3, theme: "Hero Moves & Boundaries", title: "Reset After a Setback", focus: "A changed plan is not the same as failure.", reflection: "What did not go the way you expected, and what did it teach you?", strength: "What part of your response showed persistence, honesty, flexibility, or courage?", move: "Revise one Hero Move so it fits what you know now.", affirmation: "Changing my plan after learning more is a form of progress." },
  { day: 19, week: 3, theme: "Hero Moves & Boundaries", title: "Have the Necessary Conversation", focus: "Some problems become lighter when they are spoken clearly and safely.", reflection: "What conversation have you been avoiding, postponing, or rehearsing?", strength: "What would help you stay respectful and grounded during it?", move: "Write your opening sentence and choose a safe time, place, or person for the conversation.", affirmation: "I can prepare for a difficult conversation without trying to control the outcome." },
  { day: 20, week: 3, theme: "Hero Moves & Boundaries", title: "Protect Your Attention", focus: "Attention is a resource you can direct on purpose.", reflection: "What has been pulling your attention away from what matters most?", strength: "When are you naturally more focused or less distracted?", move: "Create one short focus window with a clear beginning, ending, and fewer interruptions.", affirmation: "I can direct my attention without demanding perfect focus." },
  { day: 21, week: 3, theme: "Hero Moves & Boundaries", title: "Reflect on Your Hero Moves", focus: "Notice which actions actually helped.", reflection: "Which Hero Move this week created the most useful change, learning, or relief?", strength: "What made that move realistic enough to complete or revise?", move: "Choose one Hero Move pattern you want to repeat next week.", affirmation: "I can learn from the moves I actually make, not just the plans I imagine." },

  { day: 22, week: 4, theme: "Reflect Forward", title: "See the Pattern", focus: "Patterns become useful when they help you choose, not judge yourself.", reflection: "What pattern have you noticed across your thoughts, choices, stress, relationships, or energy this month?", strength: "What positive pattern has also been present?", move: "Write one pattern you want to interrupt and one you want to strengthen.", affirmation: "I can notice patterns without turning them into labels about who I am." },
  { day: 23, week: 4, theme: "Reflect Forward", title: "Choose What to Carry", focus: "Growth includes deciding what deserves to continue.", reflection: "What lesson, habit, relationship, value, or practice from this month is worth carrying forward?", strength: "What has helped you keep it alive so far?", move: "Choose one simple way to keep that practice visible for the next seven days.", affirmation: "I can carry forward what is useful and leave room to keep learning." },
  { day: 24, week: 4, theme: "Reflect Forward", title: "Release What Is Not Yours", focus: "Responsibility becomes healthier when it has boundaries.", reflection: "What outcome, opinion, conflict, or responsibility are you carrying that may not fully belong to you?", strength: "What is actually within your role, control, or responsibility?", move: "Write one sentence separating what is yours to do from what is not yours to control.", affirmation: "I can care deeply without carrying everything." },
  { day: 25, week: 4, theme: "Reflect Forward", title: "Practice Courage in a Small Way", focus: "Courage often looks ordinary before it looks dramatic.", reflection: "Where would one honest, respectful, or uncomfortable action move you closer to what matters?", strength: "What kind of courage have you already practiced this month?", move: "Take one safe, specific action that requires a little courage but remains within your control.", affirmation: "Courage can be quiet, specific, and practiced." },
  { day: 26, week: 4, theme: "Reflect Forward", title: "Notice the Evidence", focus: "Progress is easier to trust when you can point to evidence.", reflection: "What is different now because of something you practiced, learned, asked, changed, or completed?", strength: "Which strength contributed most to that evidence?", move: "Record three pieces of evidence of effort, learning, support, or progress from this month.", affirmation: "I can notice progress without pretending everything is finished." },
  { day: 27, week: 4, theme: "Reflect Forward", title: "Prepare for a Hard Day", focus: "A plan can make difficult moments easier to navigate.", reflection: "When you have a hard day, what usually becomes harder first: focus, patience, motivation, communication, or asking for help?", strength: "What support or practice has helped on hard days before?", move: "Create a three-step hard-day plan: pause, reach toward one support, and choose one smallest next action.", affirmation: "I can prepare support for myself before I need it most." },
  { day: 28, week: 4, theme: "Reflect Forward", title: "Serve Without Disappearing", focus: "Helping others should not require abandoning yourself.", reflection: "Where are you giving time, care, attention, or effort to someone else?", strength: "What makes that service meaningful to you?", move: "Choose one way to help while also protecting a reasonable limit for yourself.", affirmation: "I can contribute without erasing my own needs and limits." },
  { day: 29, week: 5, theme: "Integration", title: "Design Your Next 30 Days", focus: "A useful plan connects values, support, and realistic action.", reflection: "What do you want the next month to be about—not just what do you want to finish?", strength: "Which strengths and supports should be part of that month from the beginning?", move: "Write one monthly intention and three small Hero Moves that support it.", affirmation: "I can build the next month around what matters, not just what is urgent." },
  { day: 30, week: 5, theme: "Integration", title: "Reflect Forward", focus: "Finish by noticing what you want to remember.", reflection: "What did this 30-day practice teach you about how you pause, choose, ask for help, and move forward?", strength: "Which strength do you understand differently now?", move: "Write a note to your future self naming one lesson, one support, and one Hero Move you want to remember.", affirmation: "I can pause, learn, choose, ask for help, and take the next honest step." },
];

const PERMISSION_AND_SAFETY =
  "You are in charge of this experience. Keep your eyes open or closed, breathe naturally, and skip any prompt that does not feel useful. If you feel unsafe or overwhelmed, stop and reach out to a trusted person or local support.";

export function getHeroWithin30DayTranscript(item: HeroWithin30Day) {
  return [
    `Welcome. I’m Z-Girl, and this is your Hero Within audio reflection. Day ${item.day}: ${item.title}.`,
    PERMISSION_AND_SAFETY,
    item.focus,
    `Reflection: ${item.reflection}`,
    `Find the strength: ${item.strength}`,
    `Choose a Hero Move: ${item.move}`,
    `Affirmation: ${item.affirmation}`,
    "Take a moment to notice what you want to carry with you. You can write it down, revise your Hero Move, or simply return when you are ready.",
  ].join("\n\n");
}
