import type { Metadata } from "next";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { credentialRpc } from "@/lib/credentials/store";
import { credentialSessionToken } from "@/lib/credentials/session";
import PrintDecisionPacketButton from "@/components/institutions/PrintDecisionPacketButton";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Institutional Pipeline Packet", description: "Restricted Z-Girl institutional prospect and contract-handoff packet.", robots: { index: false, follow: false } };

type Opportunity={id:string;institution_id:string;opportunity_code:string;opportunity_type:string;contract_path:string;stage:string;priority:string;owner_name:string|null;source:string|null;strategic_need:string|null;use_case:string|null;estimated_value_cents:number|null;probability_percent:number;target_decision_date:string|null;target_start_date:string|null;institution_name:string;institution_type:string;institution_status:string;existing_license_code:string|null;workflow_code:string|null;workflow_status:string|null;agreement_code:string|null;agreement_status:string|null;handoff_workflow_id:string|null};
type Contact={id:string;opportunity_id:string;full_name:string;role_title:string|null;email:string|null;phone:string|null;decision_role:string;status:string};
type Activity={id:string;opportunity_id:string;activity_type:string;direction:string;summary:string;actor_name:string|null;occurred_at:string};
type Proposal={id:string;opportunity_id:string;proposal_code:string;proposal_type:string;version:number;status:string;title:string;scope_summary:string|null;proposed_value_cents:number|null;reference:string|null;sent_at:string|null;expires_at:string|null;decision_at:string|null};
type Followup={id:string;opportunity_id:string;action_text:string;due_at:string;priority:string;owner_name:string|null;status:string;completed_at:string|null};
type Dashboard={opportunities:Opportunity[];contacts:Contact[];activities:Activity[];proposals:Proposal[];followups:Followup[]};
const pretty=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());
const dollars=(c:number|null)=>typeof c==="number"?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(c/100):"—";
function Row({label,value}:{label:string;value:string}){return <div className="flex gap-3"><dt className="w-40 shrink-0 text-slate-500 print:text-slate-600">{label}</dt><dd className="font-bold">{value}</dd></div>}

export default async function PipelinePacket({params}:{params:Promise<{id:string}>}){
 const token=await credentialSessionToken();if(!token)redirect("/institutions/ops/pipeline");const{id}=await params;let dashboard:Dashboard;try{dashboard=await credentialRpc<Dashboard>("zgirl_partner_pipeline_dashboard",{p_session_token:token});}catch{redirect("/institutions/ops/pipeline")}
 const opportunity=dashboard.opportunities.find(o=>o.id===id);if(!opportunity)notFound();const contacts=dashboard.contacts.filter(c=>c.opportunity_id===id);const activities=dashboard.activities.filter(a=>a.opportunity_id===id).slice(0,25);const proposals=dashboard.proposals.filter(p=>p.opportunity_id===id);const followups=dashboard.followups.filter(f=>f.opportunity_id===id);
 return <main className="min-h-screen bg-[#061521] px-5 py-10 text-white print:bg-white print:px-0 print:py-0 print:text-black sm:px-8"><div className="mx-auto max-w-5xl"><div className="mb-6 flex flex-wrap items-center justify-between gap-3 print:hidden"><Link href="/institutions/ops/pipeline" className="button-secondary">← Partner pipeline</Link><PrintDecisionPacketButton/></div><article className="rounded-[2rem] border border-white/10 bg-white/[.035] p-7 print:rounded-none print:border-0 print:bg-white print:p-0"><header className="border-b border-white/10 pb-7 print:border-slate-300"><p className="text-xs font-black uppercase tracking-[.18em] text-[#49d8c2] print:text-slate-600">Z-Girl Institutional Pipeline Packet · v3.2</p><h1 className="mt-3 font-display text-4xl font-black">{opportunity.institution_name}</h1><p className="mt-2 text-lg font-bold">{opportunity.opportunity_code} · {pretty(opportunity.opportunity_type)}</p><p className="mt-2 text-sm text-slate-400 print:text-slate-600">Stage {pretty(opportunity.stage)} · path {pretty(opportunity.contract_path)} · priority {pretty(opportunity.priority)}</p></header>
 <section className="grid gap-5 border-b border-white/10 py-7 md:grid-cols-2 print:border-slate-300"><div><h2 className="font-display text-xl font-black">Opportunity summary</h2><dl className="mt-4 space-y-2 text-sm"><Row label="Owner" value={opportunity.owner_name||"—"}/><Row label="Source" value={opportunity.source||"—"}/><Row label="Estimated value" value={dollars(opportunity.estimated_value_cents)}/><Row label="Probability" value={`${opportunity.probability_percent}%`}/><Row label="Decision target" value={opportunity.target_decision_date||"—"}/><Row label="Start target" value={opportunity.target_start_date||"—"}/></dl></div><div><h2 className="font-display text-xl font-black">Institutional context</h2><dl className="mt-4 space-y-2 text-sm"><Row label="Institution type" value={pretty(opportunity.institution_type)}/><Row label="Institution status" value={pretty(opportunity.institution_status)}/><Row label="Existing license" value={opportunity.existing_license_code||"None"}/><Row label="Workflow" value={opportunity.workflow_code?`${opportunity.workflow_code} · ${pretty(opportunity.workflow_status||"unknown")}`:"Not handed off"}/><Row label="Agreement" value={opportunity.agreement_code?`${opportunity.agreement_code} · ${pretty(opportunity.agreement_status||"unknown")}`:"Not created"}/></dl></div></section>
 <section className="grid gap-5 border-b border-white/10 py-7 md:grid-cols-2 print:border-slate-300"><div><h2 className="font-display text-xl font-black">Strategic need</h2><p className="mt-3 text-sm leading-7 text-slate-400 print:text-slate-700">{opportunity.strategic_need||"Not yet documented."}</p></div><div><h2 className="font-display text-xl font-black">Proposed use case</h2><p className="mt-3 text-sm leading-7 text-slate-400 print:text-slate-700">{opportunity.use_case||"Not yet documented."}</p></div></section>
 <section className="border-b border-white/10 py-7 print:border-slate-300"><h2 className="font-display text-xl font-black">Decision-maker map</h2><div className="mt-4 overflow-hidden rounded-xl border border-white/10 print:border-slate-300"><table className="w-full text-left text-sm"><thead className="bg-white/[.04] print:bg-slate-100"><tr><th className="p-3">Contact</th><th className="p-3">Decision role</th><th className="p-3">Title</th><th className="p-3">Contact</th></tr></thead><tbody>{contacts.map(c=><tr key={c.id} className="border-t border-white/10 print:border-slate-300"><td className="p-3 font-bold">{c.full_name}</td><td className="p-3">{pretty(c.decision_role)}</td><td className="p-3">{c.role_title||"—"}</td><td className="p-3">{c.email||c.phone||"—"}</td></tr>)}</tbody></table></div>{contacts.length===0&&<p className="mt-3 text-sm text-slate-500">No institutional contacts mapped.</p>}</section>
 <section className="border-b border-white/10 py-7 print:border-slate-300"><h2 className="font-display text-xl font-black">Proposal record</h2><div className="mt-4 space-y-3">{proposals.map(p=><div key={p.id} className="rounded-xl border border-white/10 p-4 print:border-slate-300"><p className="font-bold">{p.proposal_code} · v{p.version} · {pretty(p.status)}</p><p className="mt-1 text-sm">{p.title} · {dollars(p.proposed_value_cents)}</p>{p.scope_summary&&<p className="mt-2 text-xs leading-6 text-slate-500 print:text-slate-600">{p.scope_summary}</p>}<p className="mt-2 text-xs text-slate-500 print:text-slate-600">Reference {p.reference||"—"} · expires {p.expires_at||"—"}</p></div>)}{proposals.length===0&&<p className="text-sm text-slate-500">No proposals recorded.</p>}</div></section>
 <section className="grid gap-5 border-b border-white/10 py-7 md:grid-cols-2 print:border-slate-300"><div><h2 className="font-display text-xl font-black">Open follow-up</h2><div className="mt-3 space-y-2">{followups.filter(f=>f.status==="open").map(f=><div key={f.id} className="rounded-xl border border-white/10 p-3 text-sm print:border-slate-300"><p className="font-bold">{f.action_text}</p><p className="mt-1 text-xs text-slate-500">Due {new Date(f.due_at).toLocaleString()} · {pretty(f.priority)} · {f.owner_name||"unassigned"}</p></div>)}{followups.filter(f=>f.status==="open").length===0&&<p className="text-sm text-slate-500">No open follow-up.</p>}</div></div><div><h2 className="font-display text-xl font-black">Recent interaction history</h2><div className="mt-3 space-y-2">{activities.slice(0,8).map(a=><div key={a.id} className="text-sm"><p className="font-bold">{a.summary}</p><p className="text-xs text-slate-500">{pretty(a.activity_type)} · {new Date(a.occurred_at).toLocaleString()}</p></div>)}</div></div></section>
 <footer className="pt-7 text-xs leading-6 text-slate-500 print:text-slate-600"><p><strong className="text-slate-300 print:text-black">Governance note:</strong> This packet is a private institutional business-development and decision aid. Proposal and pipeline values are not payment records. Proposal acceptance does not activate a license. Contract authority flows only through the governed institutional agreement and release process.</p><p className="mt-3">Do not include participant reflection text, youth/student/athlete rosters, diagnoses, counseling or therapy notes, safeguarding narratives, clinical records, clergy/spiritual-direction records, or sports-medicine records.</p></footer></article></div></main>;
}
