import type { Metadata } from "next";
import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";
import CommerceLeadForm from "@/components/CommerceLeadForm";
import CommercialHumanHero from "@/components/CommercialHumanHero";

export const metadata:Metadata={title:"Athlete Team Pilot",description:"A four-week Hero Within athlete mindset and character pilot for one team, school, league, or youth organization."};
const included=["One team, school, club, league, church-sports, or youth organization","Coach or team-leader orientation","Four-week Hero Within reflection sequence","Athlete worksheets and digital samples","Parent and caregiver information sheet","Accessible and inclusive participation guidance","Implementation check-in and completion feedback","Pilot findings summary and next-step recommendations"];
const weeks=[["Week 1","Focus & composure","Pregame reset, controllables, and one-next-play language."],["Weeks 2–3","Mistakes & culture","Reset skills, coachability, encouragement, accountability, and sportsmanship."],["Week 4","Reflect forward","Strengths, adjustments, identity beyond results, and next-season recommendations."]];
export default function AthletePilotPage(){return <main className="min-h-screen bg-[#061521] text-white"><SiteHeader/><div className="mx-auto max-w-6xl px-5 py-10 sm:px-8 lg:px-12 lg:py-14"><Link href="/athletes" className="text-sm font-bold text-slate-400">← Athlete Hub</Link><div className="mt-6"><CommercialHumanHero variant="athlete" ctaHref="#interest" ctaLabel="Request a team pilot"/></div><section className="mt-8 grid gap-5 lg:grid-cols-[1fr_.72fr]"><div className="rounded-[2rem] border border-white/10 bg-white/[.035] p-6 sm:p-8"><p className="section-kicker">Four-week supported implementation</p><h2 className="mt-2 font-display text-3xl font-black">A usable team experience—not just app access.</h2><p className="mt-3 text-sm leading-7 text-slate-300">The pilot gives athletes private reflection, coaches a bounded implementation structure, and families clear information without creating a surveillance dashboard.</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{included.map(i=><div key={i} className="rounded-2xl border border-white/10 bg-[#071925] p-4 text-sm font-bold leading-6 text-slate-200"><span className="mr-2 text-[#76ead6]">✓</span>{i}</div>)}</div></div><aside className="rounded-[2rem] border border-[#49d8c2]/20 bg-[#0a2030]/90 p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-[#76ead6]">Founding pilot range</p><p className="mt-3 font-display text-4xl font-black">$1,500–$2,500</p><p className="mt-3 text-sm leading-7 text-slate-400">One team or organization. Multiple teams, seasonal support, customization, or organization-wide licensing are scoped separately.</p><div className="mt-5 rounded-2xl border border-white/10 bg-white/[.04] p-4 text-sm leading-6 text-slate-300">Pilot pricing is a commercial offer—not a charitable donation—and does not grant access to private athlete reflections.</div><Link href="/partners" className="mt-5 block text-sm font-black text-[#76ead6]">Partner and sponsored-access pathways →</Link></aside></section><section className="mt-8 grid gap-4 md:grid-cols-3">{weeks.map(([tag,title,copy])=><article key={tag} className="rounded-3xl border border-white/10 bg-[#071925] p-6"><span className="text-xs font-black uppercase tracking-[.18em] text-[#76ead6]">{tag}</span><h2 className="mt-3 text-2xl font-black">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-400">{copy}</p></article>)}</section><section id="interest" className="mt-10"><CommerceLeadForm leadType="team-pilot" defaultOffer="athlete-team-pilot" heading="Request the founding team pilot." intro="Share the team or organization, sport or activity, age range, season timing, group size, and desired outcomes. Do not include private medical, injury, mental-health, or safeguarding information." submitLabel="Send team pilot inquiry"/></section></div></main>}
