import type { Metadata } from "next";
import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";
import HumanContextStrip from "@/components/HumanContextStrip";
import GuidedMarketSampler, { type MarketScenario } from "@/components/GuidedMarketSampler";

export const metadata: Metadata = { title: "Athlete Reflection", description: "Private athlete reflection with a human-centered path to trusted support." };
const scenarios: MarketScenario[] = [
{id:"pregame",label:"Before competition",tag:"Pregame focus",standardPrompt:"Notice what your mind and body are doing before the game. You do not need to eliminate every nerve. You need a clear job, steady effort, and one next play.",simplifiedPrompt:"Nerves are okay. Focus on one job and one play at a time.",reflection:"What can you control when competition begins?",simplifiedReflection:"What is one thing you can control?",heroMoves:["Take three slow breaths and name my first responsibility.","Use one short cue: steady, ready, next play.","Encourage a teammate before focusing on my own role.","Ask my coach one clear question about my assignment."],closing:"Confidence is trust that you can respond to the next moment with effort and composure."},
{id:"mistake",label:"After a mistake",tag:"Reset",standardPrompt:"A mistake is information, not your identity. Notice the frustration, learn what is useful, and return your attention to the next decision.",simplifiedPrompt:"The mistake happened. Learn one thing and return to the next play.",reflection:"What does a strong reset look like right now?",simplifiedReflection:"What can you do on the next play?",heroMoves:["Use a reset breath and say, next play.","Correct one technique instead of replaying the whole mistake.","Respond to coaching without arguing or shutting down.","Support a teammate and rejoin the team’s plan."],closing:"Resilience is the skill of returning. Your next response can show more about your character than the mistake itself."},
{id:"postgame",label:"After the game",tag:"Reflect forward",standardPrompt:"Separate the result from the learning. Look for one strength and one adjustment.",simplifiedPrompt:"Name one thing that worked and one thing to improve.",reflection:"What should you carry forward from this performance?",simplifiedReflection:"What will you keep doing, and what will you change?",heroMoves:["Write one strength and one practice goal.","Thank a teammate, coach, official, or supporter respectfully.","Take responsibility for one attitude or effort choice.","Recover, rest, and return to practice with a plan."],closing:"Your value is bigger than the scoreboard. Use the result as feedback while protecting your identity and relationships."}
];
export default function AthleteStartPage(){return <main className="min-h-screen bg-[#061521] text-white"><SiteHeader/><div className="mx-auto max-w-6xl px-5 py-10 sm:px-8 lg:px-12 lg:py-14"><div className="mb-7 flex flex-wrap items-center justify-between gap-4"><Link href="/athletes" className="text-sm font-bold text-slate-400">← Athlete Hub</Link><span className="rounded-full border border-[#49d8c2]/25 bg-[#49d8c2]/10 px-4 py-2 text-xs font-bold text-[#a6f5e8]">Private by default</span></div><HumanContextStrip variant="athlete"/><div className="mt-8"><GuidedMarketSampler eyebrow="Hero Within Athlete" title="Reset, reflect, and choose the next play." intro="Use a short reflection before competition, after a mistake, or after the game. When another person can help, Z-Girl can prepare you for that conversation." scenarios={scenarios} accent="teal" supportLabel="Choose a coach, parent, athletic staff member, school professional, or another trusted adult when support would help."/></div><div className="mt-8 grid gap-4 md:grid-cols-3"><a href="/resources/Hero_Within_Athlete_Reflection_Starter_Pack.pdf" download className="edition-card"><span className="section-kicker">Download</span><h2 className="mt-2 text-xl font-black">Athlete Starter Pack</h2></a><Link href="/athletes/coach" className="edition-card"><span className="section-kicker">Team use</span><h2 className="mt-2 text-xl font-black">Coach Toolkit</h2></Link><Link href="/athletes/pilot" className="edition-card"><span className="section-kicker">Organizations</span><h2 className="mt-2 text-xl font-black">Team Pilot</h2></Link></div></div></main>}
