"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Role={roleKey:string;institutionId:string|null};
type Context={operatorId:string|null;displayName:string;email:string|null;authMethod:string;breakGlass:boolean;roles:Role[]};
type Institution={id:string;name:string;institutionCode?:string;institutionType?:string;status?:string};
type Review={id:string;reviewCode:string;reviewType:string;status:string;periodStart:string|null;periodEnd:string|null;completedAt:string|null;summary:string};
type TenantDashboard={institution:Institution;accessReviews:Review[]};
type Report={id:string;reportCode:string;reportType:string;status:string;sourceReviewId:string|null;periodStart:string;periodEnd:string;title:string;executiveSummary:string;preparedBy:string;createdAt:string;finalizedAt:string|null};
type Attestation={id:string;attestationCode:string;reportId:string|null;reviewId:string|null;attestationType:string;status:string;attestorName:string;attestorTitle:string;statement:string;reference:string;createdAt:string;attestedAt:string|null};
type AuditPackage={id:string;packageCode:string;reportId:string;sourceReviewId:string|null;packageType:string;status:string;generatedBy:string;createdAt:string;manifest:Record<string,unknown>};
type Evidence={context:Context;reports:Report[];attestations:Attestation[];packages:AuditPackage[]};

const pretty=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());
const today=()=>new Date().toISOString().slice(0,10);
const yearAgo=()=>{const d=new Date();d.setFullYear(d.getFullYear()-1);return d.toISOString().slice(0,10)};
const attestationFor=(type:string)=>type==="access_review"?"access_review_completion":type==="annual_governance"?"annual_access_governance":type;
const packageFor=(type:string)=>type==="access_review"?"access_review_evidence":type;
const defaultStatement=(type:string)=>type==="access_review_completion"?"I attest that the referenced institutional access review was completed through the Z-Girl administrative governance process and that the recorded decisions reflect the reviewed administrative access assignments as of the report period.":type==="annual_access_governance"?"I attest that the referenced annual access-governance report reflects the administrative access records reviewed for the stated reporting period and that unresolved access actions are identified in the supporting evidence.":type==="sso_readiness"?"I attest that the referenced SSO readiness evidence reflects the administrative onboarding state reviewed for this institution. This attestation does not itself activate an identity provider or grant a Z-Girl role.":"I attest that the referenced offboarding closeout evidence reflects the administrative access-removal review and recorded implementation references for the stated institution and period.";

async function json<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,headers:{"Content-Type":"application/json",...(init?.headers||{})},cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||"request_failed");return d as T;}

export default function AccessGovernanceEvidenceConsole(){
 const[state,setState]=useState<"loading"|"ready"|"unauthorized">("loading");const[context,setContext]=useState<Context|null>(null);const[institutions,setInstitutions]=useState<Institution[]>([]);const[institutionId,setInstitutionId]=useState("");const[tenant,setTenant]=useState<TenantDashboard|null>(null);const[evidence,setEvidence]=useState<Evidence|null>(null);const[notice,setNotice]=useState("");const[busy,setBusy]=useState(false);const[tab,setTab]=useState<"reports"|"attestations"|"packages">("reports");
 const isOwner=useMemo(()=>!!context&&(context.breakGlass||context.roles.some(r=>r.roleKey==="system_owner"&&r.institutionId===null)),[context]);
 const canPrepare=useMemo(()=>!!context&&(isOwner||context.roles.some(r=>r.roleKey==="institutional_admin"&&(r.institutionId===null||r.institutionId===institutionId))),[context,institutionId,isOwner]);
 const completedReviews=useMemo(()=>tenant?.accessReviews?.filter(r=>r.status==="completed")||[],[tenant]);

 async function loadInstitution(id:string){if(!id)return;const [t,e]=await Promise.all([json<{ok:true;dashboard:TenantDashboard}>(`/api/institutions/ops/dashboard?institutionId=${encodeURIComponent(id)}`),json<{ok:true;evidence:Evidence}>(`/api/institutions/ops/dashboard?mode=evidenceDashboard&institutionId=${encodeURIComponent(id)}`)]);setTenant(t.dashboard);setEvidence(e.evidence);}
 async function refresh(){if(institutionId)await loadInstitution(institutionId);}
 async function act(body:Record<string,unknown>,message:string){setBusy(true);setNotice("");try{await json<{ok:true}>("/api/institutions/ops/portfolio/action",{method:"POST",body:JSON.stringify(body)});setNotice(message);await refresh();}catch(e){setNotice(e instanceof Error?pretty(e.message):"Operation failed");}finally{setBusy(false);}}
 useEffect(()=>{void(async()=>{try{const c=await json<{ok:true;context:Context}>("/api/institutions/auth/context");setContext(c.context);const d=await json<{ok:true;directory:{institutions:Institution[]}}>("/api/institutions/ops/dashboard?mode=tenantDirectory");const list=d.directory.institutions||[];setInstitutions(list);const first=list[0]?.id||"";setInstitutionId(first);if(first)await loadInstitution(first);setState("ready");}catch{setState("unauthorized");}})();},[]);
 useEffect(()=>{if(state==="ready"&&institutionId)void loadInstitution(institutionId);},[institutionId,state]);

 if(state==="loading")return <Panel>Loading access-governance evidence…</Panel>;
 if(state==="unauthorized")return <Panel><h2 className="font-display text-2xl font-black">Institutional access required</h2><p className="mt-3 text-sm leading-7 text-slate-400">Sign in with an authorized named operator identity to view governance evidence.</p><a href="/institutions/auth" className="button-primary mt-5 inline-flex">Institutional sign in</a></Panel>;
 if(!institutions.length)return <Panel><h2 className="font-display text-2xl font-black">No institutional scope is available.</h2><p className="mt-3 text-sm leading-7 text-slate-400">Evidence reporting begins after an institution and named administrative access are established.</p></Panel>;

 return <div className="space-y-6">
  <Panel><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#76ead6]">Access evidence · v3.7</p><h2 className="mt-2 font-display text-3xl font-black">{tenant?.institution.name||"Institution"}</h2><p className="mt-2 max-w-3xl text-sm leading-7 text-slate-400">Prepare administrative governance evidence, preserve human attestations, and package reproducible audit manifests without copying participant reflections or credential-assessment detail.</p></div><label className="min-w-72 text-xs font-black uppercase tracking-[.12em] text-slate-400">Institution<select className="input mt-2 w-full" value={institutionId} onChange={e=>setInstitutionId(e.target.value)}>{institutions.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label></div></Panel>
  <div className="grid gap-4 sm:grid-cols-3"><Metric label="Governance reports" value={evidence?.reports.length||0}/><Metric label="Attestations" value={evidence?.attestations.length||0}/><Metric label="Audit packages" value={evidence?.packages.length||0}/></div>
  {notice&&<div className="rounded-2xl border border-[#76ead6]/20 bg-[#49d8c2]/[.07] p-4 text-sm font-bold text-[#b8fff3]">{notice}</div>}
  <div className="flex flex-wrap gap-2">{(["reports","attestations","packages"] as const).map(t=><button key={t} className={tab===t?"button-primary":"button-secondary"} onClick={()=>setTab(t)}>{pretty(t)}</button>)}</div>
  {tab==="reports"&&<Reports institutionId={institutionId} completedReviews={completedReviews} reports={evidence?.reports||[]} canPrepare={canPrepare} isOwner={isOwner} busy={busy} context={context} onAct={act}/>} 
  {tab==="attestations"&&<Attestations attestations={evidence?.attestations||[]} reports={evidence?.reports||[]} institutionId={institutionId} canPrepare={canPrepare} isOwner={isOwner} busy={busy} onAct={act}/>} 
  {tab==="packages"&&<Packages packages={evidence?.packages||[]} reports={evidence?.reports||[]}/>} 
 </div>;
}

function Reports({institutionId,completedReviews,reports,canPrepare,isOwner,busy,context,onAct}:{institutionId:string;completedReviews:Review[];reports:Report[];canPrepare:boolean;isOwner:boolean;busy:boolean;context:Context|null;onAct:(b:Record<string,unknown>,m:string)=>Promise<void>}){
 const[type,setType]=useState("annual_governance"),[start,setStart]=useState(yearAgo()),[end,setEnd]=useState(today()),[sourceReviewId,setSourceReviewId]=useState(""),[title,setTitle]=useState("Annual Institutional Access Governance Report"),[summary,setSummary]=useState(""),[preparedBy,setPreparedBy]=useState(context?.displayName||"");
 useEffect(()=>{if(type==="access_review")setTitle("Institutional Access Review Evidence Report");else if(type==="annual_governance")setTitle("Annual Institutional Access Governance Report");else if(type==="sso_readiness")setTitle("Institutional SSO Readiness Evidence Report");else setTitle("Institutional Offboarding Closeout Report");},[type]);
 return <div className="space-y-6">{canPrepare&&<Panel><p className="section-kicker">Prepare evidence report</p><h3 className="mt-2 font-display text-2xl font-black">Freeze administrative governance facts for human review.</h3><form className="mt-5 grid gap-3 lg:grid-cols-2" onSubmit={(e:FormEvent)=>{e.preventDefault();void onAct({action:"tenant_create_governance_report",institutionId,reportType:type,periodStart:start,periodEnd:end,sourceReviewId:type==="access_review"?sourceReviewId:"",title,executiveSummary:summary,preparedBy},"Draft governance report prepared.");}}><label className="text-xs font-black uppercase tracking-[.12em] text-slate-400">Report type<select className="input mt-2 w-full" value={type} onChange={e=>setType(e.target.value)}><option value="annual_governance">Annual governance</option><option value="access_review">Completed access review</option><option value="sso_readiness">SSO readiness</option><option value="offboarding_closeout">Offboarding closeout</option></select></label><label className="text-xs font-black uppercase tracking-[.12em] text-slate-400">Source review<select className="input mt-2 w-full" value={sourceReviewId} onChange={e=>setSourceReviewId(e.target.value)} disabled={type!=="access_review"}><option value="">{type==="access_review"?"Select completed review":"Not required"}</option>{completedReviews.map(r=><option key={r.id} value={r.id}>{r.reviewCode} · {r.periodEnd||r.completedAt||"completed"}</option>)}</select></label><label className="text-xs font-black uppercase tracking-[.12em] text-slate-400">Period start<input className="input mt-2 w-full" type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="text-xs font-black uppercase tracking-[.12em] text-slate-400">Period end<input className="input mt-2 w-full" type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label className="text-xs font-black uppercase tracking-[.12em] text-slate-400 lg:col-span-2">Title<input className="input mt-2 w-full" value={title} onChange={e=>setTitle(e.target.value)} maxLength={220}/></label><label className="text-xs font-black uppercase tracking-[.12em] text-slate-400">Prepared by<input className="input mt-2 w-full" value={preparedBy} onChange={e=>setPreparedBy(e.target.value)} maxLength={120}/></label><div/><label className="text-xs font-black uppercase tracking-[.12em] text-slate-400 lg:col-span-2">Executive summary<textarea className="input mt-2 min-h-28 w-full" value={summary} onChange={e=>setSummary(e.target.value)} maxLength={2400}/></label><div className="lg:col-span-2"><button disabled={busy||type==="access_review"&&!sourceReviewId} className="button-primary">Prepare draft report</button></div></form></Panel>}
 <Panel><p className="section-kicker">Report register</p><div className="mt-5 space-y-3">{reports.map(r=><div key={r.id} className="rounded-xl border border-white/10 bg-[#04111b] p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><div className="font-black">{r.reportCode} · {r.title}</div><div className="mt-1 text-xs text-slate-400">{pretty(r.reportType)} · {pretty(r.status)} · {r.periodStart} → {r.periodEnd}</div></div><div className="flex flex-wrap gap-2"><a href={`/institutions/ops/evidence/report/${r.id}`} className="button-secondary">Open report</a>{r.status==="draft"&&isOwner&&<button disabled={busy} className="button-primary" onClick={()=>void onAct({action:"tenant_finalize_governance_report",reportId:r.id},"Governance report finalized.")}>Finalize</button>}</div></div></div>)}{!reports.length&&<Empty>No governance reports yet.</Empty>}</div></Panel></div>;
}

function Attestations({attestations,reports,institutionId,canPrepare,isOwner,busy,onAct}:{attestations:Attestation[];reports:Report[];institutionId:string;canPrepare:boolean;isOwner:boolean;busy:boolean;onAct:(b:Record<string,unknown>,m:string)=>Promise<void>}){const finalized=reports.filter(r=>r.status==="finalized");return <div className="space-y-6">{canPrepare&&finalized.length>0&&<Panel><p className="section-kicker">Prepare attestation</p><div className="mt-4 grid gap-3 md:grid-cols-[1fr_auto]">{finalized.map(r=><div key={r.id} className="contents"><div className="rounded-xl border border-white/10 bg-[#04111b] p-4"><div className="font-black">{r.reportCode}</div><div className="mt-1 text-xs text-slate-400">{r.title}</div></div><button disabled={busy} className="button-secondary" onClick={()=>void onAct({action:"tenant_prepare_attestation",institutionId,reportId:r.id,attestationType:attestationFor(r.reportType)},"Draft attestation prepared.")}>Prepare</button></div>)}</div></Panel>}<Panel><p className="section-kicker">Attestation register</p><div className="mt-5 space-y-4">{attestations.map(a=><AttestationCard key={a.id} item={a} isOwner={isOwner} busy={busy} onAct={onAct}/>)}{!attestations.length&&<Empty>No attestations yet.</Empty>}</div></Panel></div>}

function AttestationCard({item,isOwner,busy,onAct}:{item:Attestation;isOwner:boolean;busy:boolean;onAct:(b:Record<string,unknown>,m:string)=>Promise<void>}){const[name,setName]=useState(item.attestorName||""),[title,setTitle]=useState(item.attestorTitle||""),[statement,setStatement]=useState(item.statement||defaultStatement(item.attestationType)),[reference,setReference]=useState(item.reference||"");return <div className="rounded-xl border border-white/10 bg-[#04111b] p-4"><div className="font-black">{item.attestationCode} · {pretty(item.attestationType)}</div><div className="mt-1 text-xs text-slate-400">{pretty(item.status)}{item.attestedAt?` · attested ${new Date(item.attestedAt).toLocaleDateString()}`:""}</div>{item.status==="attested"?<div className="mt-4 text-sm leading-7 text-slate-300"><p>{item.statement}</p><p className="mt-2 font-bold">{item.attestorName} · {item.attestorTitle}</p>{item.reference&&<p className="text-xs text-slate-500">Reference: {item.reference}</p>}</div>:isOwner?<div className="mt-4 grid gap-3 md:grid-cols-2"><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Attestor name"/><input className="input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Attestor title"/><textarea className="input min-h-28 md:col-span-2" value={statement} onChange={e=>setStatement(e.target.value)} maxLength={1800}/><input className="input md:col-span-2" value={reference} onChange={e=>setReference(e.target.value)} placeholder="Decision / approval reference (optional)" maxLength={300}/><div className="md:col-span-2"><button disabled={busy||name.length<2||title.length<2||statement.length<10} className="button-primary" onClick={()=>void onAct({action:"tenant_attest_access_governance",attestationId:item.id,attestorName:name,attestorTitle:title,statement,reference},"Access-governance attestation recorded.")}>Record attestation</button></div></div>:<p className="mt-3 text-sm text-amber-200">System Owner attestation is pending.</p>}</div>}

function Packages({packages,reports}:{packages:AuditPackage[];reports:Report[]}){const byReport=new Map(reports.map(r=>[r.id,r]));return <Panel><p className="section-kicker">Audit package register</p><p className="mt-2 text-sm leading-7 text-slate-400">Each package is a manifest of administrative source evidence. The manifest is not a compliance certificate and contains no participant reflection content.</p><div className="mt-5 space-y-3">{packages.map(p=><div key={p.id} className="rounded-xl border border-white/10 bg-[#04111b] p-4"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><div className="font-black">{p.packageCode} · {pretty(p.packageType)}</div><div className="mt-1 text-xs text-slate-400">{byReport.get(p.reportId)?.reportCode||"Report"} · {pretty(p.status)} · generated {new Date(p.createdAt).toLocaleDateString()}</div></div><div className="flex gap-2"><a href={`/institutions/ops/evidence/report/${p.reportId}`} className="button-secondary">Report packet</a><button className="button-secondary" onClick={()=>downloadManifest(p)}>Download manifest</button></div></div></div>)}{!packages.length&&<Empty>No audit packages yet. System Owner can generate one from a finalized report.</Empty>}</div></Panel>}

function downloadManifest(item:AuditPackage){const blob=new Blob([JSON.stringify({packageCode:item.packageCode,packageType:item.packageType,status:item.status,createdAt:item.createdAt,manifest:item.manifest},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${item.packageCode}.json`;a.click();URL.revokeObjectURL(url)}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><p className="text-xs font-black uppercase tracking-[.12em] text-slate-500">{label}</p><p className="mt-2 font-display text-3xl font-black">{value}</p></div>}
function Panel({children}:{children:React.ReactNode}){return <section className="rounded-[2rem] border border-white/10 bg-white/[.035] p-6 sm:p-7">{children}</section>}
function Empty({children}:{children:React.ReactNode}){return <p className="text-sm leading-7 text-slate-500">{children}</p>}
