"use client";

import { useEffect, useState } from "react";

type Institution={id:string;name:string};
type Report={id:string;reportCode:string;reportType:string;status:string;title:string};
type Evidence={reports:Report[]};
const pretty=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());
const packageType=(t:string)=>t==="access_review"?"access_review_evidence":t;
async function api<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,headers:{"Content-Type":"application/json",...(init?.headers||{})},cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||"request_failed");return d as T}

export default function AccessGovernancePackageControls(){const[institutions,setInstitutions]=useState<Institution[]>([]),[institutionId,setInstitutionId]=useState(""),[reports,setReports]=useState<Report[]>([]),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);async function load(id:string){if(!id)return;const e=await api<{ok:true;evidence:Evidence}>(`/api/institutions/ops/dashboard?mode=evidenceDashboard&institutionId=${encodeURIComponent(id)}`);setReports((e.evidence.reports||[]).filter(r=>r.status==="finalized"))}useEffect(()=>{void(async()=>{try{const d=await api<{ok:true;directory:{institutions:Institution[]}}>("/api/institutions/ops/dashboard?mode=tenantDirectory");const list=d.directory.institutions||[];setInstitutions(list);const first=list[0]?.id||"";setInstitutionId(first);if(first)await load(first)}catch{}})()},[]);useEffect(()=>{if(institutionId)void load(institutionId)},[institutionId]);if(!institutions.length)return null;return <section className="mt-8 rounded-[2rem] border border-white/10 bg-white/[.035] p-6 sm:p-7"><p className="section-kicker">Finalize evidence bundle</p><h2 className="mt-2 font-display text-2xl font-black">Create immutable audit-package manifest</h2><p className="mt-2 text-sm leading-7 text-slate-400">This action is authorized separately by the server. It creates a manifest referencing a finalized governance report and related attestations; it does not change access permissions.</p><label className="mt-5 block text-xs font-black uppercase tracking-[.12em] text-slate-400">Institution<select className="input mt-2 w-full max-w-xl" value={institutionId} onChange={e=>setInstitutionId(e.target.value)}>{institutions.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label>{notice&&<div className="mt-4 rounded-xl border border-white/10 p-3 text-sm text-slate-300">{notice}</div>}<div className="mt-5 space-y-3">{reports.map(r=><div key={r.id} className="flex flex-col gap-3 rounded-xl border border-white/10 bg-[#04111b] p-4 md:flex-row md:items-center md:justify-between"><div><div className="font-black">{r.reportCode}</div><div className="text-xs text-slate-400">{r.title} · {pretty(r.reportType)}</div></div><button disabled={busy} className="button-secondary" onClick={()=>void(async()=>{setBusy(true);setNotice("");try{await api("/api/institutions/ops/portfolio/action",{method:"POST",body:JSON.stringify({action:"tenant_create_audit_package",reportId:r.id,packageType:packageType(r.reportType),generatedBy:"Institutional governance workspace"})});setNotice("Audit-package manifest generated.");await load(institutionId)}catch(e){setNotice(e instanceof Error?pretty(e.message):"Operation failed")}finally{setBusy(false)}})()}>Generate package</button></div>)}{!reports.length&&<p className="text-sm text-slate-500">No finalized governance report is currently available for packaging.</p>}</div></section>}
