"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

type Props={id:string};
const list=(v:any)=>Array.isArray(v)?v:[];

export default function BoardGovernancePacket({id}:Props){
 const [packet,setPacket]=useState<any>(null);const [error,setError]=useState("");
 useEffect(()=>{void (async()=>{try{const res=await fetch(`/api/institutions/ops/board-governance/packet?id=${encodeURIComponent(id)}`,{cache:"no-store"});const data=await res.json();if(!res.ok)throw new Error(data?.error||"Unable to load board governance packet");setPacket(data.packet);}catch(e:any){setError(e?.message||"Unable to load board governance packet");}})();},[id]);
 if(error)return <section className="mx-auto max-w-5xl px-5 py-16"><p className="rounded-2xl border border-red-300/20 bg-red-300/[.06] p-5 text-red-100">{error}</p></section>;
 if(!packet)return <section className="mx-auto max-w-5xl px-5 py-16 text-slate-400">Loading board governance packet…</section>;
 const pack=packet.pack||{},inst=packet.institution||{},snap=packet.snapshot||{},summary=snap.summary||{},evidence=snap.evidenceIndex||{};
 return <article className="mx-auto max-w-6xl px-5 py-10 text-slate-100 print:max-w-none print:bg-white print:px-8 print:text-black">
  <div className="mb-8 flex flex-wrap items-center justify-between gap-3 print:hidden"><Link href="/institutions/governance-board" className="button-secondary">← Board workspace</Link><button className="button-primary" onClick={()=>window.print()}>Print / Save PDF</button></div>
  <header className="border-b border-white/15 pb-7 print:border-black/20"><p className="text-xs uppercase tracking-[.2em] text-slate-500">Z-Girl · Institutional governance reporting · v3.9</p><h1 className="mt-3 font-display text-4xl font-black sm:text-5xl">{pack.title}</h1><p className="mt-3 text-lg text-slate-300 print:text-slate-700">{inst.name} · {inst.institutionCode}</p><div className="mt-4 grid gap-2 text-sm text-slate-400 sm:grid-cols-2 lg:grid-cols-4 print:text-slate-700"><span>Pack: {pack.packCode}</span><span>Status: {pack.status}</span><span>Period: {pack.periodStart} → {pack.periodEnd}</span><span>Prepared for: {pack.preparedFor||"—"}</span></div></header>

  {pack.executiveSummary&&<section className="mt-8"><h2 className="font-display text-2xl font-black">Executive summary</h2><p className="mt-3 whitespace-pre-wrap leading-7 text-slate-300 print:text-slate-800">{pack.executiveSummary}</p></section>}

  <section className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Governance items",summary.calendarItems||0],["Due",summary.calendarDue||0],["Evidence reports",summary.governanceReports||0],["Retention reviews",summary.retentionReviewsDue||0]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-white/10 p-4 print:border-black/20"><p className="text-xs uppercase tracking-[.16em] text-slate-500">{l}</p><p className="mt-1 text-3xl font-black">{v}</p></div>)}</section>

  <section className="mt-10 break-inside-avoid"><h2 className="font-display text-2xl font-black">Governance calendar</h2><div className="mt-4 overflow-x-auto"><table className="w-full border-collapse text-left text-sm"><thead><tr className="border-b border-white/15 print:border-black/20"><th className="py-2 pr-3">Due</th><th className="py-2 pr-3">Item</th><th className="py-2 pr-3">Type</th><th className="py-2 pr-3">Owner</th><th className="py-2">Status</th></tr></thead><tbody>{list(snap.calendarItems).map((c:any)=><tr key={c.id||c.calendarCode} className="border-b border-white/10 print:border-black/10"><td className="py-2 pr-3">{c.dueDate}</td><td className="py-2 pr-3">{c.title}</td><td className="py-2 pr-3">{c.itemType}</td><td className="py-2 pr-3">{c.ownerName||"Unassigned"}</td><td className="py-2">{c.status}</td></tr>)}</tbody></table>{!list(snap.calendarItems).length&&<p className="mt-3 text-sm text-slate-500">No governance items for this period.</p>}</div></section>

  <section className="mt-10 break-inside-avoid"><h2 className="font-display text-2xl font-black">Executive action owners</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{list(snap.actionOwners).map((o:any)=><div key={o.ownerName} className="rounded-2xl border border-white/10 p-4 print:border-black/20"><strong>{o.ownerName}</strong><p className="mt-2 text-sm text-slate-400 print:text-slate-700">Open {o.openItems||0} · Due {o.dueItems||0} · Completed {o.completedItems||0} · Next {o.nextDueDate||"—"}</p></div>)}</div></section>

  <section className="mt-10"><h2 className="font-display text-2xl font-black">Administrative evidence index</h2><div className="mt-5 space-y-7"><Evidence title="Governance reports" rows={list(evidence.reports)} code="reportCode" type="reportType" date="finalizedAt"/><Evidence title="Attestations" rows={list(evidence.attestations)} code="attestationCode" type="attestationType" date="attestedAt"/><Evidence title="Audit packages" rows={list(evidence.packages)} code="packageCode" type="packageType" date="createdAt"/><Evidence title="Retention review register" rows={list(evidence.retention)} code="retentionCode" type="evidenceType" date="nextReviewDate"/></div></section>

  <footer className="mt-12 border-t border-white/15 pt-6 text-xs leading-6 text-slate-500 print:border-black/20 print:text-slate-700"><strong>Governance/data boundary.</strong> This packet is an administrative governance record. It excludes participant private reflections, participant case records, credential assessment detail, clinical or counseling records, clergy/spiritual-direction records and sports-medicine records. It is not a regulatory certification, legal compliance opinion, accreditation or independent audit opinion. Finalization freezes this administrative snapshot; it does not execute agreements, grant access, issue credentials, activate licenses or alter payment/revenue state.</footer>
 </article>;
}

function Evidence({title,rows,code,type,date}:{title:string;rows:any[];code:string;type:string;date:string}){return <div className="break-inside-avoid"><h3 className="font-semibold">{title}</h3>{rows.length?<div className="mt-2 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-white/15 print:border-black/20"><th className="py-2 pr-3">Code</th><th className="py-2 pr-3">Type</th><th className="py-2 pr-3">Status</th><th className="py-2">Date</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id||r[code]} className="border-b border-white/10 print:border-black/10"><td className="py-2 pr-3">{r[code]}</td><td className="py-2 pr-3">{r[type]}</td><td className="py-2 pr-3">{r.status}</td><td className="py-2">{r[date]||"—"}</td></tr>)}</tbody></table></div>:<p className="mt-2 text-sm text-slate-500">None in this period.</p>}</div>}
