"use client";

import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";

type Mode="login"|"enroll";
async function call(url:string,body:Record<string,unknown>){const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body),cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||"request_failed");return d;}
const pretty=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());

export default function InstitutionOperatorAccess(){
 const router=useRouter();const[mode,setMode]=useState<Mode>("login");const[email,setEmail]=useState("");const[code,setCode]=useState("");const[newCode,setNewCode]=useState("");const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setNotice("");try{if(mode==="login")await call("/api/institutions/auth/login",{email,accessCode:code});else await call("/api/institutions/auth/accept-invite",{email,inviteCode:code,newAccessCode:newCode});router.push("/institutions/ops/portfolio");router.refresh();}catch(err){setNotice(err instanceof Error?pretty(err.message):"Access failed");}finally{setBusy(false);}}
 return <div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]">
  <section className="rounded-[2rem] border border-white/10 bg-white/[.035] p-7 sm:p-9"><p className="text-xs font-black uppercase tracking-[.18em] text-[#76ead6]">Named institutional access · v3.5</p><h2 className="mt-3 font-display text-3xl font-black">Sign in as a named operator.</h2><p className="mt-4 text-sm leading-7 text-slate-400">Named access ties institutional actions to a specific operator and role. Shared break-glass access remains separate for emergency owner use.</p><div data-guide-target="auth-mode" className="mt-6 flex gap-2">{(["login","enroll"] as Mode[]).map(x=><button key={x} onClick={()=>{setMode(x);setNotice("");setCode("");setNewCode("");}} className={`rounded-full px-4 py-2 text-xs font-black ${mode===x?"bg-[#49d8c2] text-[#04151c]":"border border-white/10"}`}>{x==="login"?"Sign in":"Accept invite"}</button>)}</div><form onSubmit={submit} className="mt-6 grid gap-3"><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="Operator email" className="input"/><input type="password" required minLength={24} maxLength={200} value={code} onChange={e=>setCode(e.target.value)} placeholder={mode==="login"?"Personal access code":"One-time invitation code"} className="input"/>{mode==="enroll"&&<><input type="password" required minLength={24} maxLength={200} value={newCode} onChange={e=>setNewCode(e.target.value)} placeholder="Create personal access code (24+ characters)" className="input"/><p className="text-xs leading-6 text-slate-500">The invitation code is single-use. Your new personal code is stored only as a SHA-256 hash and should not be shared.</p></>}<button disabled={busy} className="button-primary disabled:opacity-50">{busy?"Working…":mode==="login"?"Open institutional operations":"Enroll and sign in"}</button></form>{notice&&<p className="mt-4 rounded-xl border border-rose-300/20 bg-rose-300/[.07] p-3 text-sm font-bold text-rose-100">{notice}</p>}</section>
  <aside className="space-y-5"><div className="rounded-[2rem] border border-white/10 bg-[#04111b] p-7"><p className="text-xs font-black uppercase tracking-[.16em] text-amber-200">SSO-ready foundation</p><h3 className="mt-3 font-display text-2xl font-black">Institutional SSO is mapped, not silently enabled.</h3><p className="mt-3 text-sm leading-7 text-slate-400">v3.5 can bind a named operator to a verified Supabase Auth user UUID and distinguish ordinary Supabase Auth from SAML SSO. A SAML-only operator cannot exchange a non-SAML session.</p><div className="mt-5 grid gap-3 text-sm text-slate-300">{["Google Workspace / Microsoft Entra / Okta compatible through SAML 2.0 when the project plan/provider is configured.","SSO user UUID—not email alone—becomes the durable identity after first verified binding.","Changing auth mode or suspending an operator revokes that operator’s active sessions.","No SSO identity receives a role merely because it shares an institutional email domain."].map(x=><div key={x} className="rounded-xl border border-white/10 bg-white/[.025] p-3">✓ {x}</div>)}</div></div><div className="rounded-[2rem] border border-white/10 bg-white/[.03] p-7"><h3 className="font-display text-xl font-black">Access hierarchy</h3><p className="mt-3 text-sm leading-7 text-slate-400">System Owner · Executive · Institutional Admin · Pipeline Manager · Credential Admin · Auditor. Roles can be global or institution-scoped where appropriate.</p></div></aside>
 </div>;
}
