"use client";

import { FormEvent,useEffect,useState } from "react";

type Context={operatorId:string|null;displayName:string;email:string|null;authMethod:string;breakGlass:boolean;roles:Array<{roleKey:string;institutionId:string|null}>};
const pretty=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());
async function req<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,headers:{"Content-Type":"application/json",...(init?.headers||{})},cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||"request_failed");return d as T;}

export default function OperatorSecuritySelfService(){
 const[state,setState]=useState<"loading"|"ready"|"unauthorized">("loading");const[context,setContext]=useState<Context|null>(null);const[current,setCurrent]=useState("");const[next,setNext]=useState("");const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
 useEffect(()=>{void (async()=>{try{const d=await req<{ok:true;context:Context}>("/api/institutions/auth/context");setContext(d.context);setState("ready");}catch{setState("unauthorized");}})();},[]);
 async function rotate(e:FormEvent){e.preventDefault();setBusy(true);setNotice("");try{await req("/api/institutions/auth/rotate",{method:"POST",body:JSON.stringify({currentCode:current,newCode:next})});setCurrent("");setNext("");setNotice("Personal access code rotated. Other active named sessions were revoked.");}catch(err){setNotice(err instanceof Error?pretty(err.message):"Rotation failed");}finally{setBusy(false);}}
 if(state==="loading")return <Panel>Loading operator security…</Panel>;
 if(state==="unauthorized")return <Panel><h2 className="font-display text-2xl font-black">Named operator session required</h2><p className="mt-3 text-sm leading-7 text-slate-400">Sign in with your named institutional operator identity to manage personal access.</p><a href="/institutions/auth" className="button-primary mt-5 inline-flex">Institutional sign in</a></Panel>;
 if(!context)return null;
 return <div className="grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><Panel><p className="text-xs font-black uppercase tracking-[.18em] text-[#76ead6]">Current session</p><h2 className="mt-2 font-display text-3xl font-black">{context.displayName}</h2><p className="mt-2 text-sm text-slate-400">{context.breakGlass?"Break-glass owner session":`${context.email} · ${pretty(context.authMethod)}`}</p><div className="mt-5 flex flex-wrap gap-2">{context.roles.map((r,i)=><span key={`${r.roleKey}-${r.institutionId}-${i}`} className="rounded-full border border-white/10 px-3 py-1 text-xs font-black">{pretty(r.roleKey)}{r.institutionId?" · Scoped":" · Global"}</span>)}</div>{context.breakGlass&&<div className="mt-5 rounded-2xl border border-amber-300/20 bg-amber-300/[.06] p-4 text-sm leading-7 text-amber-100">Break-glass access does not have a personal operator code. Rotate the emergency owner secret only through Identity & Access Administration / Credential Operations security.</div>}</Panel><Panel><p className="section-kicker">Personal security</p><h3 className="mt-2 font-display text-2xl font-black">Rotate my personal access code</h3><p className="mt-3 text-sm leading-7 text-slate-400">Available to named operators using Personal Code authentication. The new value must be at least 24 characters; only its SHA-256 hash is stored.</p>{context.breakGlass||context.authMethod!=="local_code"?<div className="mt-5 rounded-xl border border-white/10 bg-[#04111b] p-4 text-sm text-slate-400">Personal-code rotation is not applicable to this {pretty(context.authMethod)} session.</div>:<form onSubmit={rotate} className="mt-5 grid gap-3"><input type="password" required minLength={24} maxLength={200} value={current} onChange={e=>setCurrent(e.target.value)} placeholder="Current personal access code" className="input"/><input type="password" required minLength={24} maxLength={200} value={next} onChange={e=>setNext(e.target.value)} placeholder="New personal access code (24+ characters)" className="input"/><button disabled={busy} className="button-primary disabled:opacity-50">{busy?"Rotating…":"Rotate personal access"}</button></form>}{notice&&<p className="mt-4 rounded-xl border border-[#76ead6]/20 bg-[#49d8c2]/[.07] p-3 text-sm font-bold text-[#b8fff3]">{notice}</p>}</Panel></div>;
}
function Panel({children}:{children:React.ReactNode}){return <div className="rounded-[2rem] border border-white/10 bg-white/[.035] p-6 sm:p-7">{children}</div>}
