"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type J=Record<string,unknown>;
type Detail={pilot:J;institution:J;readiness:{passed:number;total:number;missing:string[];ready:boolean};intake:J|null;team:J[];cohorts:J[];milestones:J[];metrics:J[];evidence:J[];permissions:J|null;competencySignals:J[];closeout:J|null;events:J[]};
const s=(r:J|null|undefined,k:string)=>typeof r?.[k]==="string"?r[k] as string:"";
const n=(r:J|null|undefined,k:string)=>typeof r?.[k]==="number"?r[k] as number:0;
const pretty=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());
const money=(cents:number,currency:string)=>cents?new Intl.NumberFormat("en-US",{style:"currency",currency:currency||"USD",maximumFractionDigits:0}).format(cents/100):"Not set in Z-Girl — use GLS proposal/contract record";
async function call<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,cache:"no-store",headers:{"Content-Type":"application/json",...(init?.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||"request_failed");return d as T;}

function usePilot(pilotId:string){const[data,setData]=useState<Detail|null>(null);const[error,setError]=useState("");const load=async()=>{try{const d=await call<{ok:true;dashboard:Detail}>(`/api/institutions/ops/pilots/dashboard?pilotId=${encodeURIComponent(pilotId)}`);setData(d.dashboard);setError("");}catch(e){setError(e instanceof Error?e.message:"request_failed");}};useEffect(()=>{void load();},[pilotId]);return{data,error,reload:load};}

export function PilotEvidencePackage({pilotId}:{pilotId:string}){
 const{data,error}=usePilot(pilotId);if(error)return <State text={pretty(error)}/>;if(!data)return <State text="Loading evidence package…"/>;
 const p=data.pilot,i=data.institution,latest=data.metrics[0];
 const claimCounts=useMemo(()=>Object.fromEntries(["observed","participant_reported","facilitator_reported","administrator_reported","system_analytic","administrative_fact"].map(k=>[k,data.evidence.filter(e=>s(e,"claim_type")===k).length])),[data.evidence]);
 return <Packet title="Institutional Pilot Evidence Package" subtitle={`${s(i,"name")} · ${s(p,"pilot_code")}`}>
  <Notice>Administrative implementation evidence only. This package is not an independent audit, clinical record, regulatory certification or proof of participant outcomes. Private reflection text is excluded.</Notice>
  <Grid><Card label="Pilot stage" value={pretty(s(p,"stage"))}/><Card label="Readiness" value={`${data.readiness.passed}/${data.readiness.total}`}/><Card label="Participant capacity" value={n(p,"participant_capacity")}/><Card label="Evidence records" value={data.evidence.length}/></Grid>
  <Section title="Implementation summary"><Text value={s(data.closeout,"implementation_summary")||"Closeout draft not yet recorded."}/><Text value={s(data.closeout,"executive_outcome_summary")||"Executive outcome summary not yet recorded."}/></Section>
  <Section title="Aggregate implementation signals"><Rows rows={[["Participants invited",String(n(latest,"participants_invited"))],["Participants activated",String(n(latest,"participants_activated"))],["Active participants",String(n(latest,"active_participants"))],["Activities started",String(n(latest,"activities_started"))],["Activities completed",String(n(latest,"activities_completed"))],["Reflection sessions",String(n(latest,"reflection_sessions"))],["Support requests",String(n(latest,"support_requests"))],["Accessibility issues",String(n(latest,"accessibility_issues"))]]}/><p className="mt-3 text-xs text-slate-500">Latest aggregate snapshot only. These are administrative/system counts, not effectiveness claims.</p></Section>
  <Section title="Evidence provenance"><div className="grid gap-3 md:grid-cols-3">{Object.entries(claimCounts).map(([k,v])=><Card key={k} label={pretty(k)} value={v}/>)}</div><div className="mt-5 space-y-3">{data.evidence.map(e=><div key={s(e,"id")} className="rounded-xl border border-white/10 p-4"><div className="flex flex-wrap gap-2 text-[10px] font-black uppercase tracking-[.1em] text-[#76ead6]"><span>{pretty(s(e,"evidence_category"))}</span><span>·</span><span>{pretty(s(e,"claim_type"))}</span><span>·</span><span>{pretty(s(e,"provenance_type"))}</span></div><p className="mt-2 text-sm leading-7 text-slate-300">{s(e,"summary")}</p><p className="mt-2 text-xs text-slate-500">{s(e,"evidence_date")} · permission: {pretty(s(e,"permission_status"))} · verified: {String(e.verified===true)}</p></div>)}{!data.evidence.length&&<Text value="No evidence has been recorded. The system does not manufacture outcome claims."/>}</div></Section>
  <Section title="Feedback / publication permissions"><Rows rows={[["Testimonial",pretty(s(data.permissions,"testimonial_status")||"not requested")],["Case study",pretty(s(data.permissions,"case_study_status")||"not requested")],["Institutional reference",pretty(s(data.permissions,"reference_status")||"not requested")],["Funder evidence",pretty(s(data.permissions,"funder_evidence_status")||"not requested")],["Permission reference",s(data.permissions,"permission_reference")||"None recorded"]]}/></Section>
  <Section title="Facilitator-learning evidence"><div className="space-y-2">{data.competencySignals.map(x=><div key={s(x,"id")} className="rounded-xl border border-white/10 p-3"><strong>{pretty(s(x,"domain"))} · {pretty(s(x,"signal_type"))}</strong><p className="mt-1 text-sm text-slate-400">{s(x,"summary")}</p></div>)}{!data.competencySignals.length&&<Text value="No facilitator-learning signals have been recorded yet."/>}</div></Section>
  <Section title="Renewal / expansion"><Rows rows={[["Renewal status",pretty(s(p,"renewal_status"))],["Expansion status",pretty(s(p,"expansion_status"))],["Renewal recommendation",s(data.closeout,"renewal_recommendation")||"Not yet recorded"],["Expansion recommendation",s(data.closeout,"expansion_recommendation")||"Not yet recorded"],["Case-study readiness",pretty(s(data.closeout,"case_study_readiness")||"not ready")]]}/></Section>
 </Packet>;
}

export function PilotCommercialPackage({pilotId}:{pilotId:string}){
 const{data,error,reload}=usePilot(pilotId);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
 if(error)return <State text={pretty(error)}/>;if(!data)return <State text="Loading commercial scope…"/>;
 const p=data.pilot,i=data.institution,intake=data.intake;
 const[capacity,setCapacity]=useState(String(n(p,"participant_capacity")||1));const[price,setPrice]=useState(n(p,"proposed_price_cents")?String(n(p,"proposed_price_cents")/100):"");const[dm,setDm]=useState(s(p,"decision_maker_name"));const[dmRole,setDmRole]=useState(s(p,"decision_maker_role"));const[dmEmail,setDmEmail]=useState(s(p,"decision_maker_email"));const[start,setStart]=useState(s(p,"planned_start_date"));const[end,setEnd]=useState(s(p,"planned_end_date"));const[renewal,setRenewal]=useState(s(p,"renewal_date"));const[next,setNext]=useState(s(p,"next_action"));
 async function save(e:FormEvent){e.preventDefault();setBusy(true);try{await call("/api/institutions/ops/pilots/scope",{method:"POST",body:JSON.stringify({pilotId,decisionMakerName:dm,decisionMakerRole:dmRole,decisionMakerEmail:dmEmail,participantCapacity:Number(capacity),proposedPriceCents:price?Math.round(Number(price)*100):null,currency:s(p,"currency")||"USD",plannedStartDate:start||null,plannedEndDate:end||null,renewalDate:renewal||null,nextAction:next,nextActionDue:null})});setNotice("Implementation-scope metadata saved. Contract/payment authority remains in GLS.");await reload();}catch(e){setNotice(e instanceof Error?pretty(e.message):"Save failed");}finally{setBusy(false);}}
 const profiles=Array.isArray(p.solution_profiles)?p.solution_profiles as string[]:[];
 return <Packet title="Institutional Pilot Commercial & Scope Package" subtitle={`${s(i,"name")} · ${s(p,"pilot_code")}`}>
  <Notice>This is a Z-Girl implementation-scope record. GLS remains the source of truth for opportunity stage, proposal, executed agreement, invoice/payment state and recognized commercial value. Public self-service checkout is not required.</Notice>
  {notice&&<div className="rounded-xl border border-[#76ead6]/20 bg-[#49d8c2]/[.06] p-4 text-sm">{notice}</div>}
  <Section title="Administrative scope controls"><form onSubmit={save} className="grid gap-3 md:grid-cols-2"><Input label="Decision maker" value={dm} set={setDm}/><Input label="Decision-maker role" value={dmRole} set={setDmRole}/><Input label="Decision-maker email" value={dmEmail} set={setDmEmail} type="email"/><Input label="Participant capacity" value={capacity} set={setCapacity} type="number"/><Input label="Proposed pilot amount (USD)" value={price} set={setPrice} type="number"/><Input label="Planned start" value={start} set={setStart} type="date"/><Input label="Planned end" value={end} set={setEnd} type="date"/><Input label="Renewal review date" value={renewal} set={setRenewal} type="date"/><div className="md:col-span-2"><Input label="Next action" value={next} set={setNext}/></div><div className="md:col-span-2"><button disabled={busy} className="button-primary">Save implementation scope</button></div></form></Section>
  <Section title="Proposal-ready description"><Text value={`Z-Girl ${profiles.map(pretty).join(" + ")||"General"} institutional pilot for ${s(i,"name")}, configured for up to ${n(p,"participant_capacity")} participants. The pilot includes readiness review, administrator/facilitator onboarding, governed cohort activation, implementation checkpoints, aggregate adoption tracking, provenance-labeled evidence capture, closeout review, and renewal/expansion recommendations. Private participant reflections are not included in institutional reporting.`}/></Section>
  <Section title="Scope of work"><Rows rows={[["Institution / profile",`${s(i,"name")} · ${pretty(s(p,"institution_profile"))}`],["Solution profile(s)",profiles.map(pretty).join(", ")||"General"],["Participant capacity",String(n(p,"participant_capacity"))],["Implementation window",`${s(p,"planned_start_date")||"TBD"} → ${s(p,"planned_end_date")||"TBD"}`],["Proposed amount",money(n(p,"proposed_price_cents"),s(p,"currency")||"USD")],["Contracting entity",s(p,"contracting_entity_name")],["Engagement nature",pretty(s(p,"engagement_nature"))],["GLS opportunity",s(p,"gls_opportunity_id")||"Not linked"],["GLS agreement",s(p,"gls_agreement_id")||"Not linked"],["GLS engagement",s(p,"gls_engagement_id")||"Not linked"],["Commercial status",pretty(s(p,"commercial_status"))]]}/></Section>
  <Section title="Implementation deliverables"><ul className="list-disc space-y-2 pl-5 text-sm leading-7 text-slate-300"><li>Institutional intake, qualification and readiness assessment.</li><li>Institution setup and role-scoped administrator/facilitator responsibilities.</li><li>Configurable cohort and approved Z-Girl profile setup.</li><li>Administrator/facilitator orientation, safety escalation route and accessibility configuration.</li><li>Launch checklist, implementation calendar and midpoint review.</li><li>Aggregate activation/activity/completion tracking without private-reflection access.</li><li>Provenance-labeled implementation evidence and feedback capture.</li><li>Closeout summary, evidence package and renewal/expansion recommendation.</li></ul></Section>
  <Section title="Assumptions / readiness"><Text value={s(intake,"implementation_environment")||"Implementation environment to be confirmed during intake."}/><Text value={s(intake,"facilitator_requirements")||"Facilitator requirements to be confirmed."}/><Text value={s(intake,"accessibility_considerations")||"Accessibility/accommodation plan to be confirmed."}/><Text value={s(intake,"risk_safety_considerations")||"Safety/escalation requirements to be confirmed."}/><Text value={s(intake,"data_privacy_requirements")||"Institutional data/privacy requirements to be confirmed."}/></Section>
  <Section title="Expansion architecture"><ul className="list-disc space-y-2 pl-5 text-sm leading-7 text-slate-300"><li>Additional cohort(s) or site(s).</li><li>Additional Z-Girl profile(s): EDU, Faith & Values, Athlete, accessibility supports.</li><li>Annual institutional license.</li><li>District/network/multi-site expansion.</li><li>Facilitator authorization/credential pathway after real pilot evidence is sufficient.</li><li>Complementary Greene Leadership System institutional offerings.</li></ul></Section>
 </Packet>;
}

export function PilotPermissions({pilotId}:{pilotId:string}){
 const{data,error,reload}=usePilot(pilotId);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");
 if(error)return <State text={pretty(error)}/>;if(!data)return <State text="Loading evidence permissions…"/>;
 const p=data.permissions;
 const[testimonial,setTestimonial]=useState(s(p,"testimonial_status")||"not_requested"),[caseStudy,setCaseStudy]=useState(s(p,"case_study_status")||"not_requested"),[reference,setReference]=useState(s(p,"reference_status")||"not_requested"),[funder,setFunder]=useState(s(p,"funder_evidence_status")||"not_requested"),[ref,setRef]=useState(s(p,"permission_reference")),[notes,setNotes]=useState(s(p,"notes"));
 async function save(e:FormEvent){e.preventDefault();setBusy(true);try{await call("/api/institutions/ops/pilots/action",{method:"POST",body:JSON.stringify({action:"save_permissions",pilotId,testimonialStatus:testimonial,caseStudyStatus:caseStudy,referenceStatus:reference,funderEvidenceStatus:funder,permissionReference:ref,notes})});setNotice("Permission statuses saved with source reference.");await reload();}catch(e){setNotice(e instanceof Error?pretty(e.message):"Save failed");}finally{setBusy(false);}}
 return <Packet title="Evidence & Publication Permissions" subtitle={s(data.institution,"name")}><Notice>“Granted” is an administrative record only when an actual permission/approval reference exists. The system does not infer consent from participation or favorable feedback.</Notice>{notice&&<div className="rounded-xl border border-[#76ead6]/20 p-4 text-sm">{notice}</div>}<form onSubmit={save} className="grid gap-4 md:grid-cols-2">{[["Testimonial",testimonial,setTestimonial,false],["Case study",caseStudy,setCaseStudy,false],["Institutional reference",reference,setReference,false],["Grant/funder evidence",funder,setFunder,true]].map(([label,value,setter,allowNA])=><label key={label as string} className="block"><span className="mb-2 block text-xs font-black uppercase tracking-[.12em] text-slate-400">{label as string}</span><select className="input w-full" value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)}>{["not_requested","requested","granted","declined","withdrawn",...(allowNA?["not_applicable"]:[])].map(v=><option key={v} value={v}>{pretty(v)}</option>)}</select></label>)}<div className="md:col-span-2"><Input label="Permission / approval reference" value={ref} set={setRef}/></div><label className="md:col-span-2"><span className="mb-2 block text-xs font-black uppercase tracking-[.12em] text-slate-400">Permission notes</span><textarea className="input min-h-28 w-full" value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="md:col-span-2"><button disabled={busy} className="button-primary">Save permission record</button></div></form></Packet>;
}

function Packet({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="space-y-6"><div className="rounded-[2rem] border border-white/10 bg-white/[.035] p-7 print:border-slate-300 print:bg-white print:text-black"><p className="text-xs font-black uppercase tracking-[.18em] text-[#76ead6] print:text-slate-600">Z-Girl Hero Within · v3.11</p><h1 className="mt-2 font-display text-4xl font-black">{title}</h1><p className="mt-2 text-sm text-slate-400 print:text-slate-600">{subtitle}</p><button onClick={()=>window.print()} className="button-secondary mt-5 print:hidden">Print / Save PDF</button></div>{children}</div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-[2rem] border border-white/10 bg-white/[.035] p-6 print:border-slate-300 print:bg-white print:text-black"><h2 className="font-display text-2xl font-black">{title}</h2><div className="mt-4">{children}</div></section>}
function Notice({children}:{children:React.ReactNode}){return <div className="rounded-2xl border border-amber-300/20 bg-amber-300/[.05] p-5 text-sm leading-7 text-amber-100 print:border-slate-300 print:bg-white print:text-black">{children}</div>}
function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{children}</div>}
function Card({label,value}:{label:string;value:string|number}){return <div className="rounded-xl border border-white/10 p-4 print:border-slate-300"><div className="text-[10px] font-black uppercase tracking-[.12em] text-slate-500">{label}</div><div className="mt-2 text-lg font-black">{value}</div></div>}
function Rows({rows}:{rows:string[][]}){return <div className="divide-y divide-white/10 print:divide-slate-200">{rows.map(([a,b])=><div key={a} className="flex items-start justify-between gap-5 py-3 text-sm"><span className="text-slate-500">{a}</span><strong className="max-w-[68%] text-right">{b}</strong></div>)}</div>}
function Text({value}:{value:string}){return <p className="mb-3 whitespace-pre-wrap text-sm leading-7 text-slate-300 print:text-black">{value}</p>}
function Input({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label className="block"><span className="mb-2 block text-xs font-black uppercase tracking-[.12em] text-slate-400">{label}</span><input className="input w-full" type={type} value={value} onChange={e=>set(e.target.value)}/></label>}
function State({text}:{text:string}){return <div className="rounded-[2rem] border border-white/10 bg-white/[.035] p-7 text-sm text-slate-400">{text}</div>}
