"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Role={roleKey:string;institutionId:string|null};
type Context={operatorId:string|null;displayName:string;email:string|null;authMethod:string;breakGlass:boolean;roles:Role[]};
type DirectoryInstitution={id:string;name:string;institutionCode?:string;institutionType?:string;status?:string};
type Institution={id:string;institutionCode:string;name:string;institutionType:string;status:string;primaryContactName?:string;primaryContactEmail?:string};
type License={id:string;licenseCode:string;licenseType:string;status:string;renewalStatus:string;effectiveDate:string;expiresAt:string;seatLimit:number;siteLimit:number;trainerLimit:number};
type Site={id:string;siteCode:string;name:string;siteType:string;status:string};
type Workflow={id:string;workflowCode:string;workflowType:string;status:string;targetStartDate?:string|null;requestedEffectiveDate?:string|null};
type Opportunity={id:string;opportunityCode:string;opportunityType:string;stage:string;priority:string;targetDecisionDate?:string|null;targetStartDate?:string|null};
type TenantOperator={operatorId:string;displayName:string;email:string;status:string;allowedAuthMode:string;lastLoginAt:string|null;roleAssignmentId:string;roleKey:string};
type Review={id:string;reviewCode:string;reviewType:string;status:string;periodStart:string|null;periodEnd:string|null;dueAt:string|null;openedAt:string|null;completedAt:string|null;summary:string;pendingItems:number;unimplementedItems:number};
type ReviewSchedule={enabled:boolean;cadence:string;nextReviewDate:string;ownerName:string}|null;
type SsoOnboarding={status:string;providerType:string;providerName:string;domainHint:string;metadataReference:string;configurationReference:string;testReference:string;technicalOwnerName:string;technicalOwnerEmail:string;activationApprovalReference:string;activatedAt:string|null;notes:string}|null;
type Dashboard={context:Context;institution:Institution;licenses:License[];sites:Site[];workflows:Workflow[];opportunities:Opportunity[];tenantOperators:TenantOperator[];accessReviews:Review[];accessReviewSchedule:ReviewSchedule;ssoOnboarding:SsoOnboarding;offboarding:unknown[]};
type ReviewItem={id:string;operatorName:string;operatorEmail:string;roleKey:string;operatorStatus:string;authMode:string;decision:string;recommendedRoleKey:string|null;decisionNote:string;decidedAt:string|null;appliedAt:string|null};
type Packet={institution:{id:string;name:string;institutionCode:string};review:Review;items:ReviewItem[]};

const pretty=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());
const today=()=>new Date().toISOString().slice(0,10);
const plusDays=(days:number)=>{const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};

async function json<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,headers:{"Content-Type":"application/json",...(init?.headers||{})},cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||"request_failed");return d as T;}

export default function TenantGovernanceConsole(){
 const[state,setState]=useState<"loading"|"ready"|"unauthorized">("loading");
 const[context,setContext]=useState<Context|null>(null);const[institutions,setInstitutions]=useState<DirectoryInstitution[]>([]);const[institutionId,setInstitutionId]=useState("");const[dash,setDash]=useState<Dashboard|null>(null);const[packet,setPacket]=useState<Packet|null>(null);const[tab,setTab]=useState<"overview"|"access"|"sso"|"offboarding">("overview");const[notice,setNotice]=useState("");const[busy,setBusy]=useState(false);
 const canManage=useMemo(()=>!!context&&(context.breakGlass||context.roles.some(r=>r.roleKey==="system_owner"&&r.institutionId===null)||context.roles.some(r=>r.roleKey==="institutional_admin"&&(r.institutionId===null||r.institutionId===institutionId))),[context,institutionId]);
 const isOwner=useMemo(()=>!!context&&(context.breakGlass||context.roles.some(r=>r.roleKey==="system_owner"&&r.institutionId===null)),[context]);

 async function loadDashboard(id:string){if(!id)return;const d=await json<{ok:true;dashboard:Dashboard}>(`/api/institutions/ops/dashboard?institutionId=${encodeURIComponent(id)}`);setDash(d.dashboard);setInstitutions(v=>v.map(i=>i.id===id&&(!i.name||i.name===id)?{...i,name:d.dashboard.institution.name,institutionCode:d.dashboard.institution.institutionCode}:i));}
 async function refresh(){if(institutionId)await loadDashboard(institutionId);if(packet)await loadPacket(packet.review.id);}
 async function loadPacket(reviewId:string){if(!institutionId)return;const d=await json<{ok:true;packet:Packet}>(`/api/institutions/ops/dashboard?mode=accessReviewPacket&institutionId=${encodeURIComponent(institutionId)}&reviewId=${encodeURIComponent(reviewId)}`);setPacket(d.packet);setTab("access");}
 async function act(body:Record<string,unknown>,message:string){setBusy(true);setNotice("");try{await json<{ok:true}>("/api/institutions/ops/portfolio/action",{method:"POST",body:JSON.stringify(body)});setNotice(message);await refresh();}catch(e){setNotice(e instanceof Error?pretty(e.message):"Operation failed");}finally{setBusy(false);}}

 useEffect(()=>{void(async()=>{try{const c=await json<{ok:true;context:Context}>("/api/institutions/auth/context");setContext(c.context);let list:DirectoryInstitution[]=[];try{const d=await json<{ok:true;directory:{institutions:DirectoryInstitution[]}}>("/api/institutions/ops/dashboard?mode=tenantDirectory");list=d.directory.institutions||[];}catch{const ids=[...new Set(c.context.roles.filter(r=>r.roleKey==="institutional_admin"&&r.institutionId).map(r=>r.institutionId as string))];list=ids.map(id=>({id,name:id}));}setInstitutions(list);const first=list[0]?.id||"";setInstitutionId(first);if(first)await loadDashboard(first);setState("ready");}catch{setState("unauthorized");}})();},[]);
 useEffect(()=>{if(state==="ready"&&institutionId)void loadDashboard(institutionId);},[institutionId]);

 if(state==="loading")return <Panel>Loading tenant governance…</Panel>;
 if(state==="unauthorized")return <Panel><h2 className="font-display text-2xl font-black">Named institutional access required</h2><p className="mt-3 text-sm leading-7 text-slate-400">Sign in with an authorized operator identity. Tenant access is derived from your role and institution scope.</p><a href="/institutions/auth" className="button-primary mt-5 inline-flex">Institutional sign in</a></Panel>;
 if(!institutions.length)return <Panel><h2 className="font-display text-2xl font-black">No tenant scope is assigned.</h2><p className="mt-3 text-sm leading-7 text-slate-400">Your identity is valid, but no institution is available to this tenant-governance view. System Owner can assign institutional scope in Identity & Access Administration.</p></Panel>;

 return <div className="space-y-6">
  <Panel><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#76ead6]">Tenant governance · v3.6</p><h2 className="mt-2 font-display text-3xl font-black">{dash?.institution.name||"Institution"}</h2><p className="mt-2 text-sm text-slate-400">Signed in as {context?.displayName}. {canManage?"Tenant governance actions are available.":"This session has tenant read-only oversight."}</p></div><label className="min-w-72 text-xs font-black uppercase tracking-[.12em] text-slate-400">Institution<select value={institutionId} onChange={e=>{setInstitutionId(e.target.value);setPacket(null);}} className="input mt-2 w-full">{institutions.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label></div></Panel>
  <div className="flex flex-wrap gap-2">{(["overview","access","sso","offboarding"] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?"button-primary":"button-secondary"}>{pretty(t)}</button>)}</div>
  {notice&&<div className="rounded-2xl border border-[#76ead6]/20 bg-[#49d8c2]/[.07] p-4 text-sm font-bold text-[#b8fff3]">{notice}</div>}
  {dash&&tab==="overview"&&<Overview dash={dash}/>} 
  {dash&&tab==="access"&&<AccessReviews dash={dash} packet={packet} canManage={canManage} isOwner={isOwner} busy={busy} onAct={act} onPacket={loadPacket}/>} 
  {dash&&tab==="sso"&&<SsoReadiness dash={dash} isOwner={isOwner}/>} 
  {dash&&tab==="offboarding"&&<Offboarding dash={dash} canManage={canManage} busy={busy} onAct={act} onPacket={loadPacket}/>} 
 </div>;
}

function Overview({dash}:{dash:Dashboard}){const active=dash.licenses.filter(l=>["active","conditional"].includes(l.status));const open=dash.accessReviews.filter(r=>["draft","open","in_review"].includes(r.status));return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Active licenses" value={active.length}/><Metric label="Sites" value={dash.sites.length}/><Metric label="Scoped operators" value={dash.tenantOperators.length}/><Metric label="Open access reviews" value={open.length}/></div><div className="grid gap-5 lg:grid-cols-2"><Panel><p className="section-kicker">License & delivery</p><div className="mt-4 space-y-3">{dash.licenses.slice(0,5).map(l=><Row key={l.id} title={l.licenseCode} detail={`${pretty(l.licenseType)} · ${pretty(l.status)} · expires ${l.expiresAt}`}/>)}{!dash.licenses.length&&<Empty>No license records yet.</Empty>}</div></Panel><Panel><p className="section-kicker">Current administrative access</p><div className="mt-4 space-y-3">{dash.tenantOperators.map(o=><Row key={o.roleAssignmentId} title={o.displayName} detail={`${pretty(o.roleKey)} · ${pretty(o.allowedAuthMode)} · ${pretty(o.status)}`}/>)}{!dash.tenantOperators.length&&<Empty>No institution-scoped named operators yet.</Empty>}</div></Panel><Panel><p className="section-kicker">Agreement / renewal workflows</p><div className="mt-4 space-y-3">{dash.workflows.slice(0,5).map(w=><Row key={w.id} title={w.workflowCode} detail={`${pretty(w.workflowType)} · ${pretty(w.status)}`}/>)}{!dash.workflows.length&&<Empty>No workflows yet.</Empty>}</div></Panel><Panel><p className="section-kicker">Partner / expansion activity</p><div className="mt-4 space-y-3">{dash.opportunities.slice(0,5).map(o=><Row key={o.id} title={o.opportunityCode} detail={`${pretty(o.opportunityType)} · ${pretty(o.stage)} · ${pretty(o.priority)}`}/>)}{!dash.opportunities.length&&<Empty>No institutional opportunities yet.</Empty>}</div></Panel></div></div>}

function AccessReviews({dash,packet,canManage,isOwner,busy,onAct,onPacket}:{dash:Dashboard;packet:Packet|null;canManage:boolean;isOwner:boolean;busy:boolean;onAct:(b:Record<string,unknown>,m:string)=>Promise<void>;onPacket:(id:string)=>Promise<void>}){const s=dash.accessReviewSchedule;const[cadence,setCadence]=useState(s?.cadence||"quarterly");const[next,setNext]=useState(s?.nextReviewDate||plusDays(90));const[owner,setOwner]=useState(s?.ownerName||"");const[type,setType]=useState("quarterly");const[due,setDue]=useState(plusDays(14));const[summary,setSummary]=useState("");return <div className="space-y-6"><Panel><p className="section-kicker">Recurring access recertification</p><h3 className="mt-2 font-display text-2xl font-black">Prepare reviews automatically; decide access manually.</h3><p className="mt-3 text-sm leading-7 text-slate-400">The daily job can prepare a draft packet when a review is due. It never changes permissions.</p>{canManage&&<form className="mt-5 grid gap-3 md:grid-cols-4" onSubmit={e=>{e.preventDefault();void onAct({action:"tenant_save_review_schedule",institutionId:dash.institution.id,cadence,nextReviewDate:next,ownerName:owner,enabled:true},"Access-review schedule saved.");}}><select value={cadence} onChange={e=>setCadence(e.target.value)} className="input"><option value="quarterly">Quarterly</option><option value="semiannual">Semiannual</option><option value="annual">Annual</option></select><input type="date" value={next} onChange={e=>setNext(e.target.value)} className="input"/><input value={owner} onChange={e=>setOwner(e.target.value)} placeholder="Review owner" className="input"/><button disabled={busy} className="button-primary">Save schedule</button></form>}</Panel>
 {canManage&&<Panel><p className="section-kicker">Human-initiated review</p><form className="mt-4 grid gap-3 md:grid-cols-[.8fr_.8fr_1.8fr_auto]" onSubmit={e=>{e.preventDefault();void onAct({action:"tenant_create_review",institutionId:dash.institution.id,reviewType:type,periodStart:"",periodEnd:today(),dueAt:due,summary},"Access review created.").then(()=>setSummary(""));}}><select value={type} onChange={e=>setType(e.target.value)} className="input"><option value="quarterly">Quarterly</option><option value="semiannual">Semiannual</option><option value="annual">Annual</option><option value="event_driven">Event driven</option><option value="sso_activation">SSO activation</option></select><input type="date" value={due} onChange={e=>setDue(e.target.value)} className="input"/><input value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Administrative purpose / reference" className="input"/><button disabled={busy} className="button-primary">Create review</button></form></Panel>}
 <Panel><p className="section-kicker">Review history</p><div className="mt-4 space-y-3">{dash.accessReviews.map(r=><div key={r.id} className="rounded-xl border border-white/10 bg-[#04111b] p-4"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><div className="font-black">{r.reviewCode}</div><div className="mt-1 text-xs text-slate-400">{pretty(r.reviewType)} · {pretty(r.status)} · {r.pendingItems} pending · {r.unimplementedItems} implementation records due</div></div><div className="flex flex-wrap gap-2">{r.status==="draft"&&canManage&&<button disabled={busy} onClick={()=>void onAct({action:"tenant_open_review",institutionId:dash.institution.id,reviewId:r.id},"Access review opened.")} className="button-secondary">Open</button>}<button onClick={()=>void onPacket(r.id)} className="button-secondary">Review packet</button></div></div></div>)}{!dash.accessReviews.length&&<Empty>No access reviews yet.</Empty>}</div></Panel>
 {packet&&<ReviewPacket packet={packet} institutionId={dash.institution.id} canManage={canManage} isOwner={isOwner} busy={busy} onAct={onAct}/>}</div>}

function ReviewPacket({packet,institutionId,canManage,isOwner,busy,onAct}:{packet:Packet;institutionId:string;canManage:boolean;isOwner:boolean;busy:boolean;onAct:(b:Record<string,unknown>,m:string)=>Promise<void>}){return <Panel><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><p className="section-kicker">Access decision packet</p><h3 className="mt-2 font-display text-2xl font-black">{packet.review.reviewCode}</h3><p className="mt-2 text-sm text-slate-400">{pretty(packet.review.status)} · {packet.items.length} assignment snapshot(s)</p></div><a href="/institutions/ops/identity" className="button-secondary">Identity administration</a></div><div className="mt-6 space-y-4">{packet.items.map(i=><ReviewItemRow key={i.id} item={i} institutionId={institutionId} reviewStatus={packet.review.status} canManage={canManage} isOwner={isOwner} busy={busy} onAct={onAct}/>) }{!packet.items.length&&<Empty>No institution-scoped assignments were present at snapshot time.</Empty>}</div>{canManage&&["open","in_review"].includes(packet.review.status)&&<button disabled={busy||packet.items.some(i=>i.decision==="pending")} onClick={()=>void onAct({action:"tenant_complete_review",institutionId,reviewId:packet.review.id,summary:packet.review.summary},"Access review completed; System Owner implementation remains separate.")} className="button-primary mt-5 disabled:opacity-40">Complete review</button>}<p className="mt-5 text-xs leading-6 text-slate-500">Retain/change/remove is an administrative decision record. Role/session changes remain in the verified v3.5 Identity Administration control; System Owner records the implementation reference here afterward.</p></Panel>}

function ReviewItemRow({item,institutionId,reviewStatus,canManage,isOwner,busy,onAct}:{item:ReviewItem;institutionId:string;reviewStatus:string;canManage:boolean;isOwner:boolean;busy:boolean;onAct:(b:Record<string,unknown>,m:string)=>Promise<void>}){const[decision,setDecision]=useState(item.decision);const[role,setRole]=useState(item.recommendedRoleKey||"institutional_admin");const[note,setNote]=useState(item.decisionNote||"");const[ref,setRef]=useState("");return <div className="rounded-2xl border border-white/10 bg-[#04111b] p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><div className="font-black">{item.operatorName}</div><div className="mt-1 text-xs text-slate-400">{item.operatorEmail} · {pretty(item.roleKey)} · {pretty(item.authMode)} · {pretty(item.operatorStatus)}</div></div><div className="text-xs font-black uppercase tracking-[.12em] text-[#76ead6]">{item.appliedAt?"Implementation recorded":pretty(item.decision)}</div></div>{canManage&&["open","in_review"].includes(reviewStatus)&&<div className="mt-4 grid gap-3 lg:grid-cols-[.7fr_.9fr_1.7fr_auto]"><select value={decision} onChange={e=>setDecision(e.target.value)} className="input"><option value="pending">Pending</option><option value="retain">Retain</option><option value="change">Change role</option><option value="remove">Remove access</option></select><select value={role} disabled={decision!=="change"} onChange={e=>setRole(e.target.value)} className="input disabled:opacity-40"><option value="institutional_admin">Institutional Admin</option><option value="pipeline_manager">Pipeline Manager</option><option value="credential_admin">Credential Admin</option></select><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Decision rationale / authority reference" className="input"/><button disabled={busy} onClick={()=>void onAct({action:"tenant_review_decision",institutionId,itemId:item.id,decision,recommendedRoleKey:role,decisionNote:note},"Access decision saved.")} className="button-secondary">Save</button></div>}{isOwner&&reviewStatus==="completed"&&["change","remove"].includes(item.decision)&&!item.appliedAt&&<div className="mt-4 grid gap-3 md:grid-cols-[1fr_auto]"><input value={ref} onChange={e=>setRef(e.target.value)} placeholder="Identity Administration implementation reference" className="input"/><button disabled={busy||ref.trim().length<3} onClick={()=>void onAct({action:"tenant_record_review_implementation",itemId:item.id,implementationReference:ref},"System Owner implementation evidence recorded.")} className="button-primary disabled:opacity-40">Record implementation</button></div>}</div>}

function SsoReadiness({dash,isOwner}:{dash:Dashboard;isOwner:boolean}){const stages=["Pre-authorize named operator","Collect institution IdP metadata reference","Configure Supabase Auth / SAML externally","Test approved operator identity","Confirm no domain-based role auto-grant","Record System Owner activation approval"] ;return <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><Panel><p className="section-kicker">SSO onboarding kit</p><h3 className="mt-2 font-display text-2xl font-black">Identity provider readiness without automatic authority.</h3><div className="mt-5 space-y-3">{stages.map((s,i)=><div key={s} className="flex gap-3 rounded-xl border border-white/10 bg-[#04111b] p-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-white/10 text-xs font-black">{i+1}</span><div><div className="font-bold">{s}</div><p className="mt-1 text-xs leading-5 text-slate-500">{i===5&&!isOwner?"System Owner approval is required for final activation evidence.":"Use a documented reference; do not store SAML private keys or confidential provider secrets here."}</p></div></div>)}</div></Panel><Panel><p className="section-kicker">Current readiness record</p><h3 className="mt-2 font-display text-2xl font-black">{dash.ssoOnboarding?pretty(dash.ssoOnboarding.status):"Not started"}</h3><p className="mt-3 text-sm leading-7 text-slate-400">v3.6 treats SSO as an onboarding/evidence workflow. Live provider configuration remains an external Supabase Auth / identity-provider action and does not grant a Z-Girl role by itself.</p><div className="mt-5 flex flex-wrap gap-2"><a href="/institutions/ops/identity" className="button-primary">Identity administration</a><a href="/institutions/auth/security" className="button-secondary">My access security</a></div></Panel></div>}

function Offboarding({dash,canManage,busy,onAct,onPacket}:{dash:Dashboard;canManage:boolean;busy:boolean;onAct:(b:Record<string,unknown>,m:string)=>Promise<void>;onPacket:(id:string)=>Promise<void>}){async function prepare(o:TenantOperator){const r=await json<{ok:true;reviewId:string}>("/api/institutions/ops/portfolio/action",{method:"POST",body:JSON.stringify({action:"tenant_create_review",institutionId:dash.institution.id,reviewType:"event_driven",periodStart:today(),periodEnd:today(),dueAt:plusDays(7),summary:`Offboarding access review for ${o.displayName} (${o.email}); current role ${pretty(o.roleKey)}. Final identity/session action remains in v3.5 Identity Administration.`})});await onPacket(r.reviewId);}
 return <div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Panel><p className="section-kicker">Governed offboarding</p><h3 className="mt-2 font-display text-2xl font-black">Review first. Execute identity changes separately.</h3><div className="mt-5 space-y-3">{dash.tenantOperators.map(o=><div key={o.roleAssignmentId} className="rounded-xl border border-white/10 bg-[#04111b] p-4"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><div className="font-black">{o.displayName}</div><div className="mt-1 text-xs text-slate-400">{o.email} · {pretty(o.roleKey)} · {pretty(o.allowedAuthMode)}</div></div>{canManage&&<button disabled={busy} onClick={()=>void prepare(o)} className="button-secondary">Prepare offboarding review</button>}</div></div>)}{!dash.tenantOperators.length&&<Empty>No scoped operator assignments to offboard.</Empty>}</div></Panel><Panel><p className="section-kicker">Final control</p><p className="mt-3 text-sm leading-7 text-slate-400">After the access review decision is completed, System Owner uses Identity & Access Administration to update roles/status and revoke sessions. Then the implementation reference is recorded in the review packet.</p><a href="/institutions/ops/identity" className="button-primary mt-5 inline-flex">Open Identity Administration</a></Panel></div>}

function Metric({label,value}:{label:string;value:number|string}){return <div className="rounded-[1.6rem] border border-white/10 bg-white/[.035] p-5"><div className="text-xs font-black uppercase tracking-[.14em] text-slate-500">{label}</div><div className="mt-2 font-display text-3xl font-black">{value}</div></div>}
function Row({title,detail}:{title:string;detail:string}){return <div className="rounded-xl border border-white/10 bg-[#04111b] p-4"><div className="font-bold">{title}</div><div className="mt-1 text-xs leading-5 text-slate-500">{detail}</div></div>}
function Empty({children}:{children:React.ReactNode}){return <p className="text-sm leading-7 text-slate-500">{children}</p>}
function Panel({children}:{children:React.ReactNode}){return <div className="rounded-[2rem] border border-white/10 bg-white/[.035] p-6 sm:p-7">{children}</div>}
