import type { Metadata } from "next";
import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";
import HumanContextStrip from "@/components/HumanContextStrip";
import GuidedMarketSampler, { type MarketScenario } from "@/components/GuidedMarketSampler";
export const metadata: Metadata={title:"Faith & Values Reflection",description:"Private values reflection with an optional human-support path."};
const scenarios:MarketScenario[]=[
{id:"courage",label:"I need courage",tag:"Courage",standardPrompt:"Courage does not mean you feel no fear. It means choosing a wise next step even while nervous.",simplifiedPrompt:"You can feel nervous and still take one brave, safe step.",reflection:"What would a courageous and caring response look like here?",simplifiedReflection:"What is one brave and kind thing you can do?",heroMoves:["Ask a trusted adult for help before I act.","Tell the truth calmly.","Try one small step instead of avoiding the whole situation.","Pause, pray or reflect, and choose words that do not harm anyone."],closing:"Courage grows through practiced choices. Your Hero Move can be small, safe, and honest."},
{id:"forgiveness",label:"I am hurt or upset",tag:"Forgiveness",standardPrompt:"You can name hurt, protect healthy boundaries, and choose not to let anger make every decision.",simplifiedPrompt:"You can name the hurt, stay safe, and choose what helps you heal.",reflection:"What do you need before you can take a healthy step toward peace?",simplifiedReflection:"What would help you feel safer or calmer?",heroMoves:["Tell a trusted adult what happened.","Use calm words to explain how the situation affected me.","Take space now and revisit the conversation later.","Choose not to retaliate while keeping a clear boundary."],closing:"Safety, truth, accountability, and support still matter."},
{id:"service",label:"I want to help",tag:"Service",standardPrompt:"Service begins by noticing what another person may need and responding with dignity.",simplifiedPrompt:"Notice a need. Help in a respectful way.",reflection:"What is one useful act of kindness or service you can complete today?",simplifiedReflection:"What is one helpful thing you can do today?",heroMoves:["Check on someone who seems left out.","Complete one helpful task.","Share time or encouragement respectfully.","Invite others to help with a community need."],closing:"Consistent care can change the atmosphere around you."}
];
export default function FaithStartPage(){return <main className="min-h-screen bg-[#061521] text-white"><SiteHeader/><div className="mx-auto max-w-6xl px-5 py-10 sm:px-8 lg:px-12 lg:py-14"><div className="mb-7 flex flex-wrap items-center justify-between gap-4"><Link href="/faith" className="text-sm font-bold text-slate-400">← Faith &amp; Values Hub</Link><span className="rounded-full border border-amber-300/25 bg-amber-300/10 px-4 py-2 text-xs font-bold text-amber-100">Values-led · participant controlled</span></div><HumanContextStrip variant="faith"/><div className="mt-8"><GuidedMarketSampler eyebrow="Faith & Values" title="Connect the moment to a value, then choose one Hero Move." intro="Reflect privately first. If another person belongs in the next step, prepare for a real conversation with family, a faith leader, mentor, or trusted adult." scenarios={scenarios} accent="gold" supportLabel="Z-Girl supports reflection and conversation preparation; trusted people remain responsible for human guidance." optionalPracticeLabel="Pause for a brief prayer, quiet reflection, or reading chosen by your family or faith community."/></div><div className="mt-8 grid gap-4 md:grid-cols-3"><Link href="/faith/christian" className="edition-card"><span className="text-xs font-black uppercase tracking-[.17em] text-amber-200">Starter pack</span><h2 className="mt-2 text-xl font-black">Christian Reflection</h2></Link><Link href="/faith/catholic" className="edition-card"><span className="text-xs font-black uppercase tracking-[.17em] text-amber-200">Preview</span><h2 className="mt-2 text-xl font-black">Catholic Faith &amp; Virtue</h2></Link><Link href="/faith/congregations" className="edition-card"><span className="text-xs font-black uppercase tracking-[.17em] text-amber-200">Group use</span><h2 className="mt-2 text-xl font-black">Congregation Toolkit</h2></Link></div></div></main>}
