import type { Metadata } from "next";
import Link from "next/link";
import SiteHeader from "@/components/SiteHeader";

export const metadata:Metadata={title:"Institutional Portfolio & Executive Reporting",description:"A governed Z-Girl executive layer for institutional growth, license health, renewal, credential capacity, implementation, and expansion reporting."};

const sections=[
 ["Portfolio truth","Unify prospects, pilots, active institutions, licenses, agreement workflows, credential capacity, implementation handoffs, renewals, and expansion opportunities without duplicating the underlying operational records."],
 ["Executive attention queue","Surface institutional renewal deadlines, approval/release work, near-term pipeline decisions, facilitator/trainer credential capacity, and executive review dates in one decision queue."],
 ["Institution health review","Assign an executive owner, health rating, strategic priority, expansion readiness, next action, and review date at the institution level—without collecting participant case data."],
 ["Board-ready snapshots","Create reproducible executive snapshots of portfolio metrics and action items so leadership can compare periods and prepare internal, board, funder, or strategic-partner reporting."],
 ["Capacity & scale","See seat utilization, trainer capacity, active credentials, expansion-ready relationships, and open growth opportunities before committing to additional sites or Train-the-Trainer scale."],
 ["Governance continuity","The command center reports on authority; it does not create authority. Existing agreement, approval, credential, license, and delivery-release gates remain controlling."],
];

export default function PortfolioCommandCenterPublicPage(){return <main className="min-h-screen bg-[#061521] text-white"><SiteHeader/><section className="relative isolate overflow-hidden border-b border-white/10"><div className="absolute inset-0 -z-20 bg-[radial-gradient(circle_at_80%_20%,rgba(73,216,194,.18),transparent_34%),radial-gradient(circle_at_15%_72%,rgba(251,191,36,.11),transparent_30%)]"/><div className="hero-grid absolute inset-0 -z-10 opacity-20"/><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><span className="eyebrow">Institutional executive operations · v3.3</span><h1 className="mt-5 max-w-5xl font-display text-5xl font-black leading-[.98] tracking-[-.045em] sm:text-6xl lg:text-7xl">Turn institutional activity into executive portfolio intelligence.</h1><p className="mt-7 max-w-4xl text-lg leading-8 text-slate-300">Z-Girl Institutional Portfolio & Executive Reporting Command Center gives leadership a governed view across acquisition, agreements, licenses, credential capacity, implementation, renewal, and expansion—without exposing participant reflections or converting a dashboard into an authority engine.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/partners#interest" className="button-primary">Request institutional fit review</Link><Link href="/institutions/executive-briefing-automation" className="button-secondary">Executive briefing automation</Link><Link href="/institutions/partner-pipeline" className="button-secondary">Partner pipeline</Link><Link href="/institutions/agreement-workflow" className="button-secondary">Agreement workflow</Link></div></div></section><section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-12"><p className="section-kicker">Executive command layer</p><h2 className="section-title">Pipeline → Contract → License → Capacity → Renewal → Expansion → Executive Reporting</h2><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{sections.map(([title,copy])=><article key={title} className="rounded-[2rem] border border-white/10 bg-white/[.035] p-7"><h3 className="font-display text-2xl font-black">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-400">{copy}</p></article>)}</div></section><section className="border-y border-white/10 bg-[#04111b]"><div className="mx-auto max-w-6xl px-5 py-20 sm:px-8 lg:px-12"><p className="section-kicker">Data boundary</p><h2 className="section-title">Executive reporting should become more useful without becoming more invasive.</h2><div className="mt-8 grid gap-3">{[
 "No participant private-reflection text appears in portfolio reporting.",
 "No youth/student/athlete case-management or diagnosis data belongs in the command center.",
 "Institution health ratings are executive business/implementation assessments—not clinical, educational, spiritual, or behavioral scores.",
 "Pipeline and proposal values remain planning metadata, not payment status or recognized revenue.",
 "A favorable portfolio rating cannot activate a credential, license, agreement, or delivery release.",
 "Board/executive snapshots preserve aggregate institutional operating information only."
].map(x=><div key={x} className="rounded-2xl border border-white/10 bg-white/[.035] p-4 text-sm leading-7 text-slate-300">✓ {x}</div>)}</div></div></section><section className="mx-auto max-w-6xl px-5 py-20 text-center sm:px-8 lg:px-12"><p className="section-kicker">Institutional operating system</p><h2 className="section-title">One relationship can now be managed from first interest through executive renewal and expansion review.</h2><p className="mx-auto mt-5 max-w-3xl text-base leading-8 text-slate-400">v3.3 provides executive portfolio visibility; v3.4 turns that portfolio truth into scheduled briefing, renewal, exception, owner-reminder, and board-packet intelligence.</p><Link href="/institutions/executive-briefing-automation" className="button-primary mt-8 inline-flex">Explore executive briefing automation</Link></section></main>}
