import type { Metadata } from "next";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { credentialRpc } from "@/lib/credentials/store";
import { credentialSessionToken } from "@/lib/credentials/session";
import PrintDecisionPacketButton from "@/components/institutions/PrintDecisionPacketButton";

export const dynamic="force-dynamic";
export const metadata:Metadata={title:"Institutional Governance Evidence Report",description:"Restricted Z-Girl institutional access-governance evidence report.",robots:{index:false,follow:false}};

type Attestation={id:string;attestationCode:string;attestationType:string;status:string;attestorName:string;attestorTitle:string;statement:string;reference:string;createdAt:string;attestedAt:string|null};
type Package={id:string;packageCode:string;packageType:string;status:string;generatedBy:string;createdAt:string;manifest:Record<string,unknown>};
type Snapshot={schemaVersion?:string;generatedAt?:string;reportingPeriod?:{start?:string;end?:string};accessSchedule?:{enabled?:boolean;cadence?:string;nextReviewDate?:string;ownerName?:string}|null;currentAccess?:Array<{operatorName:string;roleKey:string;authMode:string;operatorStatus:string;lastLoginAt:string|null;assignmentStatus:string}>;reviewHistory?:Array<{reviewCode:string;reviewType:string;status:string;periodStart:string|null;periodEnd:string|null;dueAt:string|null;completedAt:string|null;pendingItems:number;changeOrRemoveItems:number;unimplementedItems:number}>;sourceReview?:{review?:{reviewCode?:string;reviewType?:string;status?:string;periodStart?:string;periodEnd?:string;completedAt?:string;summary?:string};items?:Array<{operatorName:string;roleKey:string;operatorStatus:string;authMode:string;decision:string;recommendedRoleKey:string|null;decisionNote:string;decidedAt:string|null;appliedAt:string|null}>}|null;ssoReadiness?:Record<string,unknown>|null;offboardingHistory?:Array<Record<string,unknown>>;administrativeContext?:{licenseCount?:number;activeOrConditionalLicenseCount?:number;siteCount?:number};evidenceBoundary?:Record<string,unknown>};
type Packet={institution:{id:string;name:string;institutionCode:string;institutionType:string;status:string};report:{id:string;reportCode:string;reportType:string;status:string;sourceReviewId:string|null;periodStart:string;periodEnd:string;title:string;executiveSummary:string;preparedBy:string;createdAt:string;finalizedAt:string|null;snapshot:Snapshot};attestations:Attestation[];packages:Package[]};

const pretty=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,m=>m.toUpperCase());
const date=(v:string|null|undefined)=>v?new Date(v).toLocaleString():"—";

export default async function GovernanceEvidenceReportPage({params}:{params:Promise<{id:string}>}){const token=await credentialSessionToken();if(!token)redirect("/institutions/governance-evidence");const{id}=await params;let packet:Packet;try{packet=await credentialRpc<Packet>("zgirl_tenant_governance_report_packet",{p_session_token:token,p_report_id:id});}catch{notFound();}const s=packet.report.snapshot||{};return <main className="min-h-screen bg-[#061521] px-5 py-10 text-white print:bg-white print:px-0 print:py-0 print:text-black sm:px-8"><div className="mx-auto max-w-5xl"><div className="mb-6 flex flex-wrap items-center justify-between gap-3 print:hidden"><Link href="/institutions/governance-evidence" className="button-secondary">← Governance evidence</Link><PrintDecisionPacketButton/></div><article className="rounded-[2rem] border border-white/10 bg-white/[.035] p-7 print:rounded-none print:border-0 print:bg-white print:p-0"><header className="border-b border-white/10 pb-7 print:border-slate-300"><p className="text-xs font-black uppercase tracking-[.18em] text-[#49d8c2] print:text-slate-600">Z-Girl Access Governance Evidence · v3.7</p><h1 className="mt-3 font-display text-4xl font-black">{packet.report.title}</h1><p className="mt-2 text-lg font-bold">{packet.institution.name} · {packet.report.reportCode}</p><p className="mt-2 text-sm text-slate-400 print:text-slate-600">{pretty(packet.report.reportType)} · {pretty(packet.report.status)} · {packet.report.periodStart} → {packet.report.periodEnd}</p></header>
<section className="grid gap-5 border-b border-white/10 py-7 md:grid-cols-2 print:border-slate-300"><div><h2 className="font-display text-xl font-black">Report authority</h2><dl className="mt-4 space-y-2 text-sm"><Row label="Prepared by" value={packet.report.preparedBy||"—"}/><Row label="Created" value={date(packet.report.createdAt)}/><Row label="Finalized" value={date(packet.report.finalizedAt)}/><Row label="Source review" value={s.sourceReview?.review?.reviewCode||"—"}/></dl></div><div><h2 className="font-display text-xl font-black">Administrative context</h2><dl className="mt-4 space-y-2 text-sm"><Row label="Institution code" value={packet.institution.institutionCode}/><Row label="Institution type" value={pretty(packet.institution.institutionType)}/><Row label="License records" value={String(s.administrativeContext?.licenseCount??0)}/><Row label="Active / conditional licenses" value={String(s.administrativeContext?.activeOrConditionalLicenseCount??0)}/><Row label="Sites" value={String(s.administrativeContext?.siteCount??0)}/></dl></div></section>
<section className="border-b border-white/10 py-7 print:border-slate-300"><h2 className="font-display text-xl font-black">Executive summary</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-300 print:text-slate-700">{packet.report.executiveSummary||"No executive summary was recorded."}</p></section>
<section className="border-b border-white/10 py-7 print:border-slate-300"><h2 className="font-display text-xl font-black">Current administrative access</h2><div className="mt-5 overflow-hidden rounded-xl border border-white/10 print:border-slate-300"><table className="w-full border-collapse text-left text-sm"><thead className="bg-white/[.04] print:bg-slate-100"><tr><th className="p-3">Operator</th><th className="p-3">Role</th><th className="p-3">Authentication</th><th className="p-3">Status</th></tr></thead><tbody>{(s.currentAccess||[]).map((a,i)=><tr key={`${a.operatorName}-${a.roleKey}-${i}`} className="border-t border-white/10 print:border-slate-300"><td className="p-3 font-bold">{a.operatorName}</td><td className="p-3">{pretty(a.roleKey)}</td><td className="p-3">{pretty(a.authMode)}</td><td className="p-3">{pretty(a.assignmentStatus||a.operatorStatus)}</td></tr>)}</tbody></table></div>{!(s.currentAccess||[]).length&&<p className="mt-4 text-sm text-slate-500">No institution-scoped active operator assignments were captured.</p>}</section>
<section className="border-b border-white/10 py-7 print:border-slate-300"><h2 className="font-display text-xl font-black">Access-review history</h2><div className="mt-5 space-y-3">{(s.reviewHistory||[]).map((r,i)=><div key={`${r.reviewCode}-${i}`} className="rounded-xl border border-white/10 p-4 print:border-slate-300"><div className="font-black">{r.reviewCode} · {pretty(r.reviewType)}</div><div className="mt-1 text-xs text-slate-500">{pretty(r.status)} · {r.periodStart||"—"} → {r.periodEnd||"—"}</div><div className="mt-2 text-sm text-slate-300 print:text-slate-700">Pending {r.pendingItems} · change/remove {r.changeOrRemoveItems} · implementation refs outstanding {r.unimplementedItems}</div></div>)}{!(s.reviewHistory||[]).length&&<p className="text-sm text-slate-500">No access reviews fall inside this reporting period.</p>}</div></section>
{s.sourceReview?.review&&<section className="border-b border-white/10 py-7 print:border-slate-300"><h2 className="font-display text-xl font-black">Source access review</h2><p className="mt-2 text-sm font-bold">{s.sourceReview.review.reviewCode} · {pretty(s.sourceReview.review.status||"")}</p><div className="mt-5 overflow-hidden rounded-xl border border-white/10 print:border-slate-300"><table className="w-full border-collapse text-left text-sm"><thead className="bg-white/[.04] print:bg-slate-100"><tr><th className="p-3">Operator</th><th className="p-3">Role</th><th className="p-3">Decision</th><th className="p-3">Implemented</th></tr></thead><tbody>{(s.sourceReview.items||[]).map((i,n)=><tr key={`${i.operatorName}-${n}`} className="border-t border-white/10 print:border-slate-300"><td className="p-3 font-bold">{i.operatorName}</td><td className="p-3">{pretty(i.roleKey)}</td><td className="p-3">{pretty(i.decision)}{i.recommendedRoleKey?` → ${pretty(i.recommendedRoleKey)}`:""}</td><td className="p-3">{i.appliedAt?date(i.appliedAt):i.decision==="retain"?"No change required":"Pending evidence"}</td></tr>)}</tbody></table></div></section>}
<section className="border-b border-white/10 py-7 print:border-slate-300"><h2 className="font-display text-xl font-black">Attestations</h2><div className="mt-5 space-y-4">{packet.attestations.map(a=><div key={a.id} className="rounded-xl border border-white/10 p-4 print:border-slate-300"><div className="font-black">{a.attestationCode} · {pretty(a.attestationType)} · {pretty(a.status)}</div>{a.statement&&<p className="mt-3 text-sm leading-7 text-slate-300 print:text-slate-700">{a.statement}</p>}<p className="mt-2 text-xs text-slate-500">{a.attestorName||"Pending attestor"}{a.attestorTitle?` · ${a.attestorTitle}`:""}{a.reference?` · Ref ${a.reference}`:""}</p></div>)}{!packet.attestations.length&&<p className="text-sm text-slate-500">No attestation has been attached to this report.</p>}</div></section>
<section className="border-b border-white/10 py-7 print:border-slate-300"><h2 className="font-display text-xl font-black">Audit-package manifests</h2><div className="mt-5 space-y-3">{packet.packages.map(p=><div key={p.id} className="rounded-xl border border-white/10 p-4 print:border-slate-300"><div className="font-black">{p.packageCode} · {pretty(p.packageType)}</div><div className="mt-1 text-xs text-slate-500">{pretty(p.status)} · generated {date(p.createdAt)} · {p.generatedBy||"System Owner"}</div></div>)}{!packet.packages.length&&<p className="text-sm text-slate-500">No immutable audit-package manifest has been generated.</p>}</div></section>
<footer className="pt-7 text-xs leading-6 text-slate-500 print:text-slate-600"><p><strong className="text-slate-300 print:text-black">Evidence boundary:</strong> This is an administrative access-governance record. It is not a regulatory certification, professional licensure record, clinical record, safeguarding record, or participant outcome report.</p><p className="mt-3">Participant reflection text, youth/student/athlete case data, credential assessment answers, and practicum detail are intentionally excluded.</p></footer></article></div></main>}

function Row({label,value}:{label:string;value:string}){return <div className="flex gap-3"><dt className="w-44 shrink-0 text-slate-500 print:text-slate-600">{label}</dt><dd className="font-bold">{value}</dd></div>}
