-- Z-Girl v3.0 Institutional Credential & License Administration
-- Administrative institutional licensing layer. No participant reflection/youth case data.

create table if not exists public.zgirl_institutions (
  id uuid primary key default gen_random_uuid(),
  institution_code text not null unique,
  name text not null check (char_length(name) between 2 and 180),
  institution_type text not null check (institution_type in ('school','district','university','congregation','athletic_team','youth_org','municipal','nonprofit','other')),
  status text not null default 'prospect' check (status in ('prospect','pilot','active','paused','closed')),
  primary_contact_name text check (primary_contact_name is null or char_length(primary_contact_name) between 2 and 120),
  primary_contact_email text check (primary_contact_email is null or (position('@' in primary_contact_email)>1 and char_length(primary_contact_email)<=254)),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists zgirl_institutions_status_idx on public.zgirl_institutions(status,updated_at desc);

create table if not exists public.zgirl_institution_sites (
  id uuid primary key default gen_random_uuid(), institution_id uuid not null references public.zgirl_institutions(id) on delete cascade,
  site_code text not null unique, name text not null check (char_length(name) between 2 and 180),
  site_type text not null default 'program' check (site_type in ('school','campus','congregation','team','department','program','branch','other')),
  status text not null default 'active' check (status in ('active','paused','closed')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(institution_id,name)
);
create index if not exists zgirl_institution_sites_org_idx on public.zgirl_institution_sites(institution_id,status);

create table if not exists public.zgirl_institution_licenses (
  id uuid primary key default gen_random_uuid(), institution_id uuid not null references public.zgirl_institutions(id) on delete cascade,
  license_code text not null unique, license_type text not null check (license_type in ('pilot','annual','multisite','train_the_trainer')),
  status text not null default 'draft' check (status in ('draft','pending','active','conditional','suspended','lapsed','closed')),
  renewal_status text not null default 'not_due' check (renewal_status in ('not_due','due','in_progress','lapsed')),
  effective_date date not null, expires_at date not null, seat_limit integer not null default 1 check (seat_limit between 1 and 10000),
  site_limit integer not null default 1 check (site_limit between 1 and 1000), trainer_limit integer not null default 1 check (trainer_limit between 0 and 1000),
  allowed_profiles text[] not null default array['general']::text[] check (allowed_profiles <@ array['general','edu','faith','athlete']::text[] and cardinality(allowed_profiles)>0),
  allowed_credential_levels text[] not null default array['authorized_facilitator']::text[] check (allowed_credential_levels <@ array['authorized_facilitator','authorized_lead_facilitator','institutional_trainer']::text[] and cardinality(allowed_credential_levels)>0),
  agreement_status text not null default 'draft' check (agreement_status in ('draft','review','executed','expired','closed')),
  agreement_reference text check (agreement_reference is null or char_length(agreement_reference)<=180),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check (expires_at>effective_date)
);
create index if not exists zgirl_institution_licenses_org_idx on public.zgirl_institution_licenses(institution_id,status,expires_at);
create index if not exists zgirl_institution_licenses_renewal_idx on public.zgirl_institution_licenses(status,expires_at,renewal_status);

create table if not exists public.zgirl_institution_seat_allocations (
  id uuid primary key default gen_random_uuid(), license_id uuid not null references public.zgirl_institution_licenses(id) on delete cascade,
  candidate_id uuid not null references public.zgirl_credential_candidates(id) on delete restrict, site_id uuid references public.zgirl_institution_sites(id) on delete set null,
  credential_id uuid references public.zgirl_credentials(id) on delete set null, seat_role text not null default 'facilitator' check (seat_role in ('facilitator','lead_facilitator','institutional_trainer')),
  status text not null default 'reserved' check (status in ('reserved','active','blocked','released')),
  allocated_at timestamptz not null default now(), released_at timestamptz, updated_at timestamptz not null default now()
);
create unique index if not exists zgirl_institution_seat_active_unique on public.zgirl_institution_seat_allocations(license_id,candidate_id) where status<>'released';
create index if not exists zgirl_institution_seat_license_idx on public.zgirl_institution_seat_allocations(license_id,status);
create index if not exists zgirl_institution_seat_credential_idx on public.zgirl_institution_seat_allocations(credential_id) where credential_id is not null;

create table if not exists public.zgirl_institution_import_batches (
  id uuid primary key default gen_random_uuid(), license_id uuid not null references public.zgirl_institution_licenses(id) on delete cascade,
  source_label text check (source_label is null or char_length(source_label)<=180), rows_received integer not null default 0,
  candidates_created integer not null default 0, seats_allocated integer not null default 0, seats_updated integer not null default 0,
  rows_skipped integer not null default 0, created_at timestamptz not null default now()
);
create table if not exists public.zgirl_institution_license_events (
  id uuid primary key default gen_random_uuid(), institution_id uuid references public.zgirl_institutions(id) on delete cascade,
  license_id uuid references public.zgirl_institution_licenses(id) on delete cascade, event_type text not null,
  summary text not null check (char_length(summary) between 3 and 500), occurred_at timestamptz not null default now()
);
create index if not exists zgirl_institution_events_idx on public.zgirl_institution_license_events(occurred_at desc);

alter table public.zgirl_institutions enable row level security; alter table public.zgirl_institution_sites enable row level security;
alter table public.zgirl_institution_licenses enable row level security; alter table public.zgirl_institution_seat_allocations enable row level security;
alter table public.zgirl_institution_import_batches enable row level security; alter table public.zgirl_institution_license_events enable row level security;
revoke all on public.zgirl_institutions,public.zgirl_institution_sites,public.zgirl_institution_licenses,public.zgirl_institution_seat_allocations,public.zgirl_institution_import_batches,public.zgirl_institution_license_events from anon,authenticated;

create or replace function public.zgirl_institution_save(p_session_token text,p_institution_id uuid,p_name text,p_institution_type text,p_status text,p_contact_name text,p_contact_email text)
returns uuid language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare v_id uuid; v_code text; begin perform private.zgirl_credential_require_session(p_session_token);
if trim(coalesce(p_name,''))='' or char_length(trim(p_name))>180 then raise exception 'invalid_institution'; end if;
if p_institution_type not in ('school','district','university','congregation','athletic_team','youth_org','municipal','nonprofit','other') then raise exception 'invalid_institution_type'; end if;
if p_status not in ('prospect','pilot','active','paused','closed') then raise exception 'invalid_institution_status'; end if;
if p_institution_id is null then v_code:='ZG-ORG-'||extract(year from current_date)::int||'-'||upper(substr(replace(extensions.gen_random_uuid()::text,'-',''),1,8));
insert into public.zgirl_institutions(institution_code,name,institution_type,status,primary_contact_name,primary_contact_email) values(v_code,trim(p_name),p_institution_type,p_status,nullif(trim(p_contact_name),''),nullif(lower(trim(p_contact_email)),'')) returning id into v_id;
insert into public.zgirl_institution_license_events(institution_id,event_type,summary) values(v_id,'institution_created','Institution record created: '||trim(p_name));
else update public.zgirl_institutions set name=trim(p_name),institution_type=p_institution_type,status=p_status,primary_contact_name=nullif(trim(p_contact_name),''),primary_contact_email=nullif(lower(trim(p_contact_email)),''),updated_at=now() where id=p_institution_id returning id into v_id;
if v_id is null then raise exception 'institution_not_found'; end if; insert into public.zgirl_institution_license_events(institution_id,event_type,summary) values(v_id,'institution_updated','Institution record updated: '||trim(p_name)); end if; return v_id; end; $$;

create or replace function public.zgirl_institution_save_site(p_session_token text,p_site_id uuid,p_institution_id uuid,p_name text,p_site_type text,p_status text)
returns uuid language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare v_id uuid; v_code text; begin perform private.zgirl_credential_require_session(p_session_token);
if not exists(select 1 from public.zgirl_institutions where id=p_institution_id) then raise exception 'institution_not_found'; end if;
if p_site_type not in ('school','campus','congregation','team','department','program','branch','other') or p_status not in ('active','paused','closed') then raise exception 'invalid_site'; end if;
if p_site_id is null then v_code:='ZG-SITE-'||upper(substr(replace(extensions.gen_random_uuid()::text,'-',''),1,8)); insert into public.zgirl_institution_sites(institution_id,site_code,name,site_type,status) values(p_institution_id,v_code,trim(p_name),p_site_type,p_status) returning id into v_id;
else update public.zgirl_institution_sites set name=trim(p_name),site_type=p_site_type,status=p_status,updated_at=now() where id=p_site_id and institution_id=p_institution_id returning id into v_id; if v_id is null then raise exception 'site_not_found'; end if; end if;
insert into public.zgirl_institution_license_events(institution_id,event_type,summary) values(p_institution_id,'site_saved','Institution site saved: '||trim(p_name)); return v_id; end; $$;

create or replace function public.zgirl_institution_save_license(p_session_token text,p_license_id uuid,p_institution_id uuid,p_license_type text,p_status text,p_effective_date date,p_expires_at date,p_seat_limit integer,p_site_limit integer,p_trainer_limit integer,p_allowed_profiles text[],p_allowed_levels text[],p_agreement_status text,p_agreement_reference text)
returns uuid language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare v_id uuid; v_code text; begin perform private.zgirl_credential_require_session(p_session_token);
if not exists(select 1 from public.zgirl_institutions where id=p_institution_id) then raise exception 'institution_not_found'; end if;
if p_license_type not in ('pilot','annual','multisite','train_the_trainer') or p_status not in ('draft','pending','active','conditional','suspended','lapsed','closed') then raise exception 'invalid_license'; end if;
if p_effective_date is null or p_expires_at is null or p_expires_at<=p_effective_date then raise exception 'invalid_license_term'; end if;
if p_seat_limit<1 or p_site_limit<1 or p_trainer_limit<0 then raise exception 'invalid_license_limits'; end if;
if p_allowed_profiles is null or cardinality(p_allowed_profiles)=0 or not(p_allowed_profiles <@ array['general','edu','faith','athlete']::text[]) then raise exception 'invalid_profiles'; end if;
if p_allowed_levels is null or cardinality(p_allowed_levels)=0 or not(p_allowed_levels <@ array['authorized_facilitator','authorized_lead_facilitator','institutional_trainer']::text[]) then raise exception 'invalid_levels'; end if;
if p_agreement_status not in ('draft','review','executed','expired','closed') then raise exception 'invalid_agreement_status'; end if;
if p_license_id is null then v_code:='ZG-LIC-'||extract(year from current_date)::int||'-'||upper(substr(replace(extensions.gen_random_uuid()::text,'-',''),1,10)); insert into public.zgirl_institution_licenses(institution_id,license_code,license_type,status,effective_date,expires_at,seat_limit,site_limit,trainer_limit,allowed_profiles,allowed_credential_levels,agreement_status,agreement_reference) values(p_institution_id,v_code,p_license_type,p_status,p_effective_date,p_expires_at,p_seat_limit,p_site_limit,p_trainer_limit,p_allowed_profiles,p_allowed_levels,p_agreement_status,nullif(trim(p_agreement_reference),'')) returning id into v_id; insert into public.zgirl_institution_license_events(institution_id,license_id,event_type,summary) values(p_institution_id,v_id,'license_created','Institution license created: '||v_code);
else update public.zgirl_institution_licenses set license_type=p_license_type,status=p_status,effective_date=p_effective_date,expires_at=p_expires_at,seat_limit=p_seat_limit,site_limit=p_site_limit,trainer_limit=p_trainer_limit,allowed_profiles=p_allowed_profiles,allowed_credential_levels=p_allowed_levels,agreement_status=p_agreement_status,agreement_reference=nullif(trim(p_agreement_reference),''),renewal_status=case when p_status='lapsed' then 'lapsed' when p_expires_at<=current_date+90 then 'due' else 'not_due' end,updated_at=now() where id=p_license_id and institution_id=p_institution_id returning id into v_id; if v_id is null then raise exception 'license_not_found'; end if;
if p_status in ('suspended','lapsed','closed') then update public.zgirl_institution_seat_allocations set status='blocked',updated_at=now() where license_id=v_id and status in ('active','reserved'); elsif p_status in ('active','conditional') then update public.zgirl_institution_seat_allocations set status='active',updated_at=now() where license_id=v_id and status='blocked'; end if; insert into public.zgirl_institution_license_events(institution_id,license_id,event_type,summary) values(p_institution_id,v_id,'license_updated','Institution license updated'); end if; return v_id; end; $$;

create or replace function public.zgirl_institution_allocate_seat(p_session_token text,p_license_id uuid,p_candidate_id uuid,p_site_id uuid,p_seat_role text)
returns uuid language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare v_license public.zgirl_institution_licenses%rowtype; v_id uuid; v_count integer; v_status text; begin perform private.zgirl_credential_require_session(p_session_token); select * into v_license from public.zgirl_institution_licenses where id=p_license_id; if v_license.id is null then raise exception 'license_not_found'; end if; if v_license.status in ('suspended','lapsed','closed') then raise exception 'license_not_allocatable'; end if;
if not exists(select 1 from public.zgirl_credential_candidates where id=p_candidate_id) then raise exception 'candidate_not_found'; end if; if p_site_id is not null and not exists(select 1 from public.zgirl_institution_sites where id=p_site_id and institution_id=v_license.institution_id and status<>'closed') then raise exception 'invalid_license_site'; end if; if p_seat_role not in ('facilitator','lead_facilitator','institutional_trainer') then raise exception 'invalid_seat_role'; end if;
if p_seat_role='institutional_trainer' then select count(*) into v_count from public.zgirl_institution_seat_allocations where license_id=p_license_id and seat_role='institutional_trainer' and status<>'released'; if v_count>=v_license.trainer_limit then raise exception 'trainer_limit_reached'; end if; end if; select count(*) into v_count from public.zgirl_institution_seat_allocations where license_id=p_license_id and status<>'released'; if v_count>=v_license.seat_limit then raise exception 'seat_limit_reached'; end if;
v_status:=case when v_license.status in ('active','conditional') and v_license.effective_date<=current_date and v_license.expires_at>=current_date then 'active' else 'reserved' end; insert into public.zgirl_institution_seat_allocations(license_id,candidate_id,site_id,seat_role,status) values(p_license_id,p_candidate_id,p_site_id,p_seat_role,v_status) returning id into v_id; insert into public.zgirl_institution_license_events(institution_id,license_id,event_type,summary) values(v_license.institution_id,p_license_id,'seat_allocated','Credential seat allocated'); return v_id; end; $$;

create or replace function public.zgirl_institution_release_seat(p_session_token text,p_allocation_id uuid)
returns boolean language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare v_license uuid; v_org uuid; begin perform private.zgirl_credential_require_session(p_session_token); update public.zgirl_institution_seat_allocations set status='released',released_at=now(),updated_at=now() where id=p_allocation_id and status<>'released' returning license_id into v_license; if v_license is null then raise exception 'allocation_not_found'; end if; select institution_id into v_org from public.zgirl_institution_licenses where id=v_license; insert into public.zgirl_institution_license_events(institution_id,license_id,event_type,summary) values(v_org,v_license,'seat_released','Credential seat released'); return true; end; $$;

create or replace function public.zgirl_institution_link_credential(p_session_token text,p_allocation_id uuid,p_credential_id uuid)
returns boolean language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare v_candidate uuid; v_license uuid; v_org uuid; v_cred_candidate uuid; v_level text; v_role text; begin perform private.zgirl_credential_require_session(p_session_token); select candidate_id,license_id,seat_role into v_candidate,v_license,v_role from public.zgirl_institution_seat_allocations where id=p_allocation_id and status<>'released'; if v_candidate is null then raise exception 'allocation_not_found'; end if; select candidate_id,credential_level into v_cred_candidate,v_level from public.zgirl_credentials where id=p_credential_id; if v_cred_candidate is null then raise exception 'credential_not_found'; end if; if v_candidate<>v_cred_candidate then raise exception 'credential_candidate_mismatch'; end if;
if (v_role='facilitator' and v_level<>'authorized_facilitator') or (v_role='lead_facilitator' and v_level not in ('authorized_lead_facilitator','institutional_trainer')) or (v_role='institutional_trainer' and v_level<>'institutional_trainer') then raise exception 'credential_level_mismatch'; end if; if not exists(select 1 from public.zgirl_institution_licenses where id=v_license and v_level=any(allowed_credential_levels)) then raise exception 'credential_level_not_allowed'; end if; update public.zgirl_institution_seat_allocations set credential_id=p_credential_id,updated_at=now() where id=p_allocation_id; select institution_id into v_org from public.zgirl_institution_licenses where id=v_license; insert into public.zgirl_institution_license_events(institution_id,license_id,event_type,summary) values(v_org,v_license,'credential_linked','Program credential linked to institutional seat'); return true; end; $$;

create or replace function public.zgirl_institution_renew_license(p_session_token text,p_license_id uuid,p_new_expires_at date,p_new_seat_limit integer)
returns boolean language plpgsql security definer set search_path=pg_catalog,public,private as $$ declare v_org uuid; v_code text; begin perform private.zgirl_credential_require_session(p_session_token); if p_new_expires_at is null or p_new_expires_at<=current_date or p_new_seat_limit<1 then raise exception 'invalid_license_renewal'; end if; update public.zgirl_institution_licenses set expires_at=p_new_expires_at,seat_limit=p_new_seat_limit,status='active',renewal_status='not_due',agreement_status=case when agreement_status='expired' then 'review' else agreement_status end,updated_at=now() where id=p_license_id returning institution_id,license_code into v_org,v_code; if v_org is null then raise exception 'license_not_found'; end if; update public.zgirl_institution_seat_allocations set status='active',updated_at=now() where license_id=p_license_id and status='blocked'; insert into public.zgirl_institution_license_events(institution_id,license_id,event_type,summary) values(v_org,p_license_id,'license_renewed','Institution license renewed: '||v_code||' through '||p_new_expires_at::text); return true; end; $$;

create or replace function public.zgirl_institution_import_roster(p_session_token text,p_license_id uuid,p_source_label text,p_rows jsonb)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private,extensions as $$
declare v_license public.zgirl_institution_licenses%rowtype; v_org public.zgirl_institutions%rowtype; v_row jsonb; v_email text; v_name text; v_pathway text; v_training text; v_site_name text; v_role text; v_candidate uuid; v_site uuid; v_allocation uuid; v_rows integer:=0; v_created integer:=0; v_allocated integer:=0; v_updated integer:=0; v_skipped integer:=0; v_count integer; v_batch uuid; v_status text; begin perform private.zgirl_credential_require_session(p_session_token); select * into v_license from public.zgirl_institution_licenses where id=p_license_id; if v_license.id is null then raise exception 'license_not_found'; end if; select * into v_org from public.zgirl_institutions where id=v_license.institution_id; if jsonb_typeof(p_rows)<>'array' or jsonb_array_length(p_rows)>250 then raise exception 'invalid_roster'; end if;
for v_row in select value from jsonb_array_elements(p_rows) loop v_rows:=v_rows+1; v_email:=lower(trim(coalesce(v_row->>'email',''))); v_name:=trim(coalesce(v_row->>'fullName','')); v_pathway:=coalesce(nullif(v_row->>'pathway',''),'institutional'); v_training:=coalesce(nullif(v_row->>'trainingVersion',''),'2.7'); v_site_name:=trim(coalesce(v_row->>'siteName','')); v_role:=coalesce(nullif(v_row->>'seatRole',''),'facilitator'); if position('@' in v_email)<=1 or char_length(v_name)<2 or v_pathway not in ('general','edu','faith','athlete','institutional') or v_role not in ('facilitator','lead_facilitator','institutional_trainer') then v_skipped:=v_skipped+1; continue; end if;
select id into v_candidate from public.zgirl_credential_candidates where lower(email)=v_email; if v_candidate is null then insert into public.zgirl_credential_candidates(full_name,email,organization,pathway,status,training_version) values(v_name,v_email,v_org.name,v_pathway,'candidate',v_training) returning id into v_candidate; v_created:=v_created+1; end if; v_site:=null;
if v_site_name<>'' then select id into v_site from public.zgirl_institution_sites where institution_id=v_org.id and lower(name)=lower(v_site_name) and status<>'closed' limit 1; if v_site is null then if (select count(*) from public.zgirl_institution_sites where institution_id=v_org.id and status<>'closed')>=v_license.site_limit then v_skipped:=v_skipped+1; continue; end if; insert into public.zgirl_institution_sites(institution_id,site_code,name,site_type,status) values(v_org.id,'ZG-SITE-'||upper(substr(replace(extensions.gen_random_uuid()::text,'-',''),1,8)),v_site_name,'program','active') returning id into v_site; end if; end if;
select id into v_allocation from public.zgirl_institution_seat_allocations where license_id=p_license_id and candidate_id=v_candidate and status<>'released' limit 1; if v_allocation is not null then update public.zgirl_institution_seat_allocations set site_id=v_site,seat_role=v_role,updated_at=now() where id=v_allocation; v_updated:=v_updated+1; continue; end if; select count(*) into v_count from public.zgirl_institution_seat_allocations where license_id=p_license_id and status<>'released'; if v_count>=v_license.seat_limit then v_skipped:=v_skipped+1; continue; end if; if v_role='institutional_trainer' then select count(*) into v_count from public.zgirl_institution_seat_allocations where license_id=p_license_id and seat_role='institutional_trainer' and status<>'released'; if v_count>=v_license.trainer_limit then v_skipped:=v_skipped+1; continue; end if; end if; v_status:=case when v_license.status in ('active','conditional') and v_license.effective_date<=current_date and v_license.expires_at>=current_date then 'active' else 'reserved' end; insert into public.zgirl_institution_seat_allocations(license_id,candidate_id,site_id,seat_role,status) values(p_license_id,v_candidate,v_site,v_role,v_status); v_allocated:=v_allocated+1; end loop;
insert into public.zgirl_institution_import_batches(license_id,source_label,rows_received,candidates_created,seats_allocated,seats_updated,rows_skipped) values(p_license_id,nullif(trim(p_source_label),''),v_rows,v_created,v_allocated,v_updated,v_skipped) returning id into v_batch; insert into public.zgirl_institution_license_events(institution_id,license_id,event_type,summary) values(v_org.id,p_license_id,'roster_imported','Adult facilitator roster import processed: '||v_rows||' rows; '||v_allocated||' seats allocated; '||v_skipped||' rows skipped'); return jsonb_build_object('batchId',v_batch,'rowsReceived',v_rows,'candidatesCreated',v_created,'seatsAllocated',v_allocated,'seatsUpdated',v_updated,'rowsSkipped',v_skipped); end; $$;

create or replace function private.zgirl_process_institution_license_automation()
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare v_due integer:=0; v_lapsed integer:=0; v_license record; begin with due as (update public.zgirl_institution_licenses set renewal_status='due',updated_at=now() where status in ('active','conditional') and renewal_status='not_due' and expires_at between current_date and current_date+90 returning id) select count(*) into v_due from due; for v_license in update public.zgirl_institution_licenses set status='lapsed',renewal_status='lapsed',agreement_status=case when agreement_status='executed' then 'expired' else agreement_status end,updated_at=now() where status in ('active','conditional') and expires_at<current_date returning id,institution_id,license_code loop v_lapsed:=v_lapsed+1; update public.zgirl_institution_seat_allocations set status='blocked',updated_at=now() where license_id=v_license.id and status in ('active','reserved'); insert into public.zgirl_institution_license_events(institution_id,license_id,event_type,summary) values(v_license.institution_id,v_license.id,'license_lapsed','Institution license automatically lapsed after expiration: '||v_license.license_code); end loop; return jsonb_build_object('licensesDue',v_due,'licensesLapsed',v_lapsed,'processedAt',now()); end; $$;
revoke all on function private.zgirl_process_institution_license_automation() from public,anon,authenticated;
create or replace function public.zgirl_institution_run_automation(p_session_token text) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$ begin perform private.zgirl_credential_require_session(p_session_token); return private.zgirl_process_institution_license_automation(); end; $$;

create or replace function public.zgirl_institution_dashboard(p_session_token text)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public,private as $$ begin perform private.zgirl_credential_require_session(p_session_token); perform private.zgirl_process_institution_license_automation(); return jsonb_build_object(
'summary',jsonb_build_object('institutions',(select count(*) from public.zgirl_institutions where status<>'closed'),'currentLicenses',(select count(*) from public.zgirl_institution_licenses where status in ('active','conditional') and expires_at>=current_date),'licensesDue90',(select count(*) from public.zgirl_institution_licenses where status in ('active','conditional') and expires_at between current_date and current_date+90),'lapsedLicenses',(select count(*) from public.zgirl_institution_licenses where status='lapsed'),'activeSeats',(select count(*) from public.zgirl_institution_seat_allocations where status='active'),'reservedSeats',(select count(*) from public.zgirl_institution_seat_allocations where status='reserved'),'blockedSeats',(select count(*) from public.zgirl_institution_seat_allocations where status='blocked'),'linkedCredentials',(select count(*) from public.zgirl_institution_seat_allocations where status<>'released' and credential_id is not null)),
'institutions',coalesce((select jsonb_agg(to_jsonb(x) order by x.updated_at desc) from (select id,institution_code,name,institution_type,status,primary_contact_name,primary_contact_email,created_at,updated_at from public.zgirl_institutions order by updated_at desc limit 150)x),'[]'::jsonb),
'sites',coalesce((select jsonb_agg(to_jsonb(x) order by x.updated_at desc) from (select s.id,s.institution_id,s.site_code,s.name,s.site_type,s.status,s.created_at,s.updated_at from public.zgirl_institution_sites s order by s.updated_at desc limit 300)x),'[]'::jsonb),
'licenses',coalesce((select jsonb_agg(to_jsonb(x) order by x.updated_at desc) from (select l.id,l.institution_id,i.name institution_name,l.license_code,l.license_type,l.status,l.renewal_status,l.effective_date,l.expires_at,l.seat_limit,l.site_limit,l.trainer_limit,l.allowed_profiles,l.allowed_credential_levels,l.agreement_status,l.agreement_reference,l.created_at,l.updated_at,(select count(*) from public.zgirl_institution_seat_allocations a where a.license_id=l.id and a.status<>'released') seats_used from public.zgirl_institution_licenses l join public.zgirl_institutions i on i.id=l.institution_id order by l.updated_at desc limit 150)x),'[]'::jsonb),
'allocations',coalesce((select jsonb_agg(to_jsonb(x) order by x.updated_at desc) from (select a.id,a.license_id,a.candidate_id,a.site_id,a.credential_id,a.seat_role,a.status,a.allocated_at,a.released_at,a.updated_at,c.full_name,c.email,s.name site_name,cr.credential_id credential_code,cr.credential_level from public.zgirl_institution_seat_allocations a join public.zgirl_credential_candidates c on c.id=a.candidate_id left join public.zgirl_institution_sites s on s.id=a.site_id left join public.zgirl_credentials cr on cr.id=a.credential_id order by a.updated_at desc limit 500)x),'[]'::jsonb),
'candidates',coalesce((select jsonb_agg(to_jsonb(x) order by x.updated_at desc) from (select id,full_name,email,organization,pathway,status,training_version,updated_at from public.zgirl_credential_candidates order by updated_at desc limit 300)x),'[]'::jsonb),
'credentials',coalesce((select jsonb_agg(to_jsonb(x) order by x.updated_at desc) from (select id,credential_id,candidate_id,holder_name,organization,credential_level,status,expires_at,updated_at from public.zgirl_credentials order by updated_at desc limit 300)x),'[]'::jsonb),
'imports',coalesce((select jsonb_agg(to_jsonb(x) order by x.created_at desc) from (select id,license_id,source_label,rows_received,candidates_created,seats_allocated,seats_updated,rows_skipped,created_at from public.zgirl_institution_import_batches order by created_at desc limit 75)x),'[]'::jsonb),
'events',coalesce((select jsonb_agg(to_jsonb(x) order by x.occurred_at desc) from (select id,institution_id,license_id,event_type,summary,occurred_at from public.zgirl_institution_license_events order by occurred_at desc limit 100)x),'[]'::jsonb)); end; $$;

revoke all on function public.zgirl_institution_save(text,uuid,text,text,text,text,text) from public; revoke all on function public.zgirl_institution_save_site(text,uuid,uuid,text,text,text) from public; revoke all on function public.zgirl_institution_save_license(text,uuid,uuid,text,text,date,date,integer,integer,integer,text[],text[],text,text) from public; revoke all on function public.zgirl_institution_allocate_seat(text,uuid,uuid,uuid,text) from public; revoke all on function public.zgirl_institution_release_seat(text,uuid) from public; revoke all on function public.zgirl_institution_link_credential(text,uuid,uuid) from public; revoke all on function public.zgirl_institution_renew_license(text,uuid,date,integer) from public; revoke all on function public.zgirl_institution_import_roster(text,uuid,text,jsonb) from public; revoke all on function public.zgirl_institution_run_automation(text) from public; revoke all on function public.zgirl_institution_dashboard(text) from public;
grant execute on function public.zgirl_institution_save(text,uuid,text,text,text,text,text) to anon,authenticated; grant execute on function public.zgirl_institution_save_site(text,uuid,uuid,text,text,text) to anon,authenticated; grant execute on function public.zgirl_institution_save_license(text,uuid,uuid,text,text,date,date,integer,integer,integer,text[],text[],text,text) to anon,authenticated; grant execute on function public.zgirl_institution_allocate_seat(text,uuid,uuid,uuid,text) to anon,authenticated; grant execute on function public.zgirl_institution_release_seat(text,uuid) to anon,authenticated; grant execute on function public.zgirl_institution_link_credential(text,uuid,uuid) to anon,authenticated; grant execute on function public.zgirl_institution_renew_license(text,uuid,date,integer) to anon,authenticated; grant execute on function public.zgirl_institution_import_roster(text,uuid,text,jsonb) to anon,authenticated; grant execute on function public.zgirl_institution_run_automation(text) to anon,authenticated; grant execute on function public.zgirl_institution_dashboard(text) to anon,authenticated;
select cron.schedule('zgirl-institution-license-daily','27 10 * * *','select private.zgirl_process_institution_license_automation();');
